In [30]:
import pandas as pd

dataset_raw_rhea = pd.read_csv("RHEA_IDs.csv")
dataset_raw_rhea.RHEA_ID.unique().shape

(65640,)

In [19]:
dataset_raw_rhea[dataset_raw_rhea["RHEA_ID"] == 61844]

       RHEA_ID                 reactants                              products
49456  61844.0  CHEBI:145043;CHEBI:58885  CHEBI:15378;CHEBI:145042;CHEBI:58223

In [33]:
import pandas as pd

dataset_rhea = pd.read_csv("RHEA_enzyme_compound_pairs.csv")
dataset_rhea

,RHEA_ID,EC number,CHEBI_ID,uniprot_id,reaction_SMILES
0,10012.0,1.5.3.6,CHEBI:58413,P08159,O=O.[H]O[H].[H][C@]1(C2=CN=C(O)C=C2)CCC[NH+]1C...
1,10012.0,1.5.3.6,CHEBI:15377,P08159,O=O.[H]O[H].[H][C@]1(C2=CN=C(O)C=C2)CCC[NH+]1C...
2,10012.0,1.5.3.6,CHEBI:15379,P08159,O=O.[H]O[H].[H][C@]1(C2=CN=C(O)C=C2)CCC[NH+]1C...
3,10016.0,3.1.1.49,CHEBI:15377,Q3ZFI4,COC1=CC(/C=C/C(=O)OCC[N+](C)(C)C)=CC(OC)=C1O.[...
4,10016.0,3.1.1.49,CHEBI:16353,Q3ZFI4,COC1=CC(/C=C/C(=O)OCC[N+](C)(C)C)=CC(OC)=C1O.[...
...,...,...,...,...,...
447476,77975.0,NaN,CHEBI:128769,K2SUY0,C=C(C)CCOP(=O)([O-])OP(=O)([O-])[O-].C=C(C)CCO...
447477,77975.0,NaN,CHEBI:57623,P9WER5,C=C(C)CCOP(=O)([O-])OP(=O)([O-])[O-].C=C(C)CCO...
447478,77975.0,NaN,CHEBI:128769,P9WER5,C=C(C)CCOP(=O)([O-])OP(=O)([O-])[O-].C=C(C)CCO...
447479,77979.0,NaN,CHEBI:58179,A0A8H4CUY8,CC(C)=CCC/C(C)=C/CC/C(C)=C/CC/C(C)=C/CC/C(C)=C...
447480,77979.0,NaN,CHEBI:15377,A0A8H4CUY8,CC(C)=CCC/C(C)=C/CC/C(C)=C/CC/C(C)=C/CC/C(C)=C...

In [32]:
set(dataset_raw_rhea.RHEA_ID.unique()) - set(dataset_rhea.RHEA_ID.unique())

{10000.0,
 10001.0,
 10002.0,
 10003.0,
 10004.0,
 10005.0,
 10006.0,
 10007.0,
 10008.0,
 10009.0,
 10010.0,
 10011.0,
 10013.0,
 10014.0,
 10015.0,
 10017.0,
 10018.0,
 10019.0,
 10021.0,
 10022.0,
 10023.0,
 10024.0,
 10025.0,
 10026.0,
 10027.0,
 10029.0,
 10030.0,
 10031.0,
 10032.0,
 10033.0,
 10034.0,
 10035.0,
 10037.0,
 10038.0,
 10039.0,
 10041.0,
 10042.0,
 10043.0,
 10045.0,
 10046.0,
 10047.0,
 10049.0,
 10050.0,
 10051.0,
 10052.0,
 10053.0,
 10054.0,
 10055.0,
 10056.0,
 10057.0,
 10058.0,
 10059.0,
 10060.0,
 10061.0,
 10062.0,
 10063.0,
 10064.0,
 10065.0,
 10066.0,
 10067.0,
 10068.0,
 10069.0,
 10070.0,
 10071.0,
 10073.0,
 10074.0,
 10075.0,
 10077.0,
 10078.0,
 10079.0,
 10080.0,
 10081.0,
 10082.0,
 10083.0,
 10085.0,
 10086.0,
 10087.0,
 10088.0,
 10089.0,
 10090.0,
 10091.0,
 10093.0,
 10094.0,
 10095.0,
 10097.0,
 10098.0,
 10099.0,
 10101.0,
 10102.0,
 10103.0,
 10105.0,
 10106.0,
 10107.0,
 10108.0,
 10109.0,
 10110.0,
 10111.0,
 10112.0,
 10113.0,
 10114.0,
 10115.0,
 10117.0,
 10118.0,
 10119.0,
 10120.0,
 10121.0,
 10122.0,
 10123.0,
 10125.0,
 10126.0,
 10127.0,
 10129.0,
 10130.0,
 10131.0,
 10133.0,
 10134.0,
 10135.0,
 10137.0,
 10138.0,
 10139.0,
 10141.0,
 10142.0,
 10143.0,
 10145.0,
 10146.0,
 10147.0,
 10148.0,
 10149.0,
 10150.0,
 10151.0,
 10152.0,
 10153.0,
 10154.0,
 10155.0,
 10156.0,
 10157.0,
 10158.0,
 10159.0,
 10160.0,
 10161.0,
 10162.0,
 10163.0,
 10164.0,
 10165.0,
 10166.0,
 10167.0,
 10169.0,
 10170.0,
 10171.0,
 10173.0,
 10174.0,
 10175.0,
 10177.0,
 10178.0,
 10179.0,
 10180.0,
 10181.0,
 10182.0,
 10183.0,
 10185.0,
 10186.0,
 10187.0,
 10188.0,
 10189.0,
 10190.0,
 10191.0,
 10193.0,
 10194.0,
 10195.0,
 10197.0,
 10198.0,
 10199.0,
 10200.0,
 10201.0,
 10202.0,
 10203.0,
 10204.0,
 10205.0,
 10206.0,
 10207.0,
 10208.0,
 10209.0,
 10210.0,
 10211.0,
 10212.0,
 10213.0,
 10214.0,
 10215.0,
 10216.0,
 10217.0,
 10218.0,
 10219.0,
 10221.0,
 10222.0,
 10223.0,
 10225.0,
 10226.0,
 10227.0,
 10228.0,
 10229.0,
 10230.0,
 10231.0,
 10232.0,
 10233.0,
 10234.0,
 10235.0,
 10236.0,
 10237.0,
 10238.0,
 10239.0,
 10241.0,
 10242.0,
 10243.0,
 10245.0,
 10246.0,
 10247.0,
 10249.0,
 10250.0,
 10251.0,
 10252.0,
 10253.0,
 10254.0,
 10255.0,
 10256.0,
 10257.0,
 10258.0,
 10259.0,
 10261.0,
 10262.0,
 10263.0,
 10264.0,
 10265.0,
 10266.0,
 10267.0,
 10269.0,
 10270.0,
 10271.0,
 10272.0,
 10273.0,
 10274.0,
 10275.0,
 10277.0,
 10278.0,
 10279.0,
 10281.0,
 10282.0,
 10283.0,
 10284.0,
 10285.0,
 10286.0,
 10287.0,
 10289.0,
 10290.0,
 10291.0,
 10293.0,
 10294.0,
 10295.0,
 10296.0,
 10297.0,
 10298.0,
 10299.0,
 10300.0,
 10301.0,
 10302.0,
 10303.0,
 10304.0,
 10305.0,
 10306.0,
 10307.0,
 10313.0,
 10314.0,
 10315.0,
 10317.0,
 10318.0,
 10319.0,
 10321.0,
 10322.0,
 10323.0,
 10324.0,
 10325.0,
 10326.0,
 10327.0,
 10328.0,
 10329.0,
 10330.0,
 10331.0,
 10332.0,
 10333.0,
 10334.0,
 10335.0,
 10336.0,
 10337.0,
 10338.0,
 10339.0,
 10341.0,
 10342.0,
 10343.0,
 10344.0,
 10345.0,
 10346.0,
 10347.0,
 10349.0,
 10350.0,
 10351.0,
 10352.0,
 10353.0,
 10354.0,
 10355.0,
 10356.0,
 10357.0,
 10358.0,
 10359.0,
 10361.0,
 10362.0,
 10363.0,
 10364.0,
 10365.0,
 10366.0,
 10367.0,
 10368.0,
 10369.0,
 10370.0,
 10371.0,
 10372.0,
 10373.0,
 10374.0,
 10375.0,
 10377.0,
 10378.0,
 10379.0,
 10380.0,
 10381.0,
 10382.0,
 10383.0,
 10385.0,
 10386.0,
 10387.0,
 10388.0,
 10389.0,
 10390.0,
 10391.0,
 10392.0,
 10393.0,
 10394.0,
 10395.0,
 10396.0,
 10397.0,
 10398.0,
 10399.0,
 10400.0,
 10401.0,
 10402.0,
 10403.0,
 10409.0,
 10410.0,
 10411.0,
 10413.0,
 10414.0,
 10415.0,
 10417.0,
 10418.0,
 10419.0,
 10420.0,
 10421.0,
 10422.0,
 10423.0,
 10425.0,
 10426.0,
 10427.0,
 10429.0,
 10430.0,
 10431.0,
 10433.0,
 10434.0,
 10435.0,
 10437.0,
 10438.0,
 10439.0,
 10441.0,
 10442.0,
 10443.0,
 10445.0,
 10446.0,
 10447.0,
 10449.0,
 10450.0,
 10451.0,
 10453.0,
 10454.0,
 10455.0,
 10457.0,
 10458.0,
 10459.0,
 10460.0,
 10461.0,
 10462.0,
 10463.0,
 10464.0,
 10465.0,
 10466.0,
 10467.0,
 10469.0,
 10470.0,
 10471.0,
 10473.0,
 10474.0,
 10475.0,
 10480.0,
 10481.0,
 10482.0,
 10483.0,
 10484.0,
 10485.0,
 10486.0,
 10487.0,
 10489.0,
 10490.0,
 10491.0,
 10493.0,
 10494.0,
 10495.0,
 10500.0,
 10501.0,
 10502.0,
 10503.0,
 10508.0,
 10509.0,
 10510.0,
 10511.0,
 10516.0,
 10517.0,
 10518.0,
 10519.0,
 10521.0,
 10522.0,
 10523.0,
 10525.0,
 10526.0,
 10527.0,
 10528.0,
 10529.0,
 10530.0,
 10531.0,
 10533.0,
 10534.0,
 10535.0,
 10536.0,
 10537.0,
 10538.0,
 10539.0,
 10541.0,
 10542.0,
 10543.0,
 10548.0,
 10549.0,
 10550.0,
 10551.0,
 10553.0,
 10554.0,
 10555.0,
 10557.0,
 10558.0,
 10559.0,
 10560.0,
 10561.0,
 10562.0,
 10563.0,
 10564.0,
 10565.0,
 10566.0,
 10567.0,
 10568.0,
 10569.0,
 10570.0,
 10571.0,
 10572.0,
 10573.0,
 10574.0,
 10575.0,
 10576.0,
 10577.0,
 10578.0,
 10579.0,
 10580.0,
 10581.0,
 10582.0,
 10583.0,
 10585.0,
 10586.0,
 10587.0,
 10589.0,
 10590.0,
 10591.0,
 10592.0,
 10593.0,
 10594.0,
 10595.0,
 10597.0,
 10598.0,
 10599.0,
 10601.0,
 10602.0,
 10603.0,
 10605.0,
 10606.0,
 10607.0,
 10609.0,
 10610.0,
 10611.0,
 10612.0,
 10613.0,
 10614.0,
 10615.0,
 10617.0,
 10618.0,
 10619.0,
 10620.0,
 10621.0,
 10622.0,
 10623.0,
 10628.0,
 10629.0,
 10630.0,
 10631.0,
 10632.0,
 10633.0,
 10634.0,
 10635.0,
 10636.0,
 10637.0,
 10638.0,
 10639.0,
 10644.0,
 10645.0,
 10646.0,
 10647.0,
 10648.0,
 10649.0,
 10650.0,
 10651.0,
 10652.0,
 10653.0,
 10654.0,
 10655.0,
 10657.0,
 10658.0,
 10659.0,
 10660.0,
 10661.0,
 10662.0,
 10663.0,
 10665.0,
 10666.0,
 10667.0,
 10669.0,
 10670.0,
 10671.0,
 10672.0,
 10673.0,
 10674.0,
 10675.0,
 10676.0,
 10677.0,
 10678.0,
 10679.0,
 10680.0,
 10681.0,
 10682.0,
 10683.0,
 10685.0,
 10686.0,
 10687.0,
 10689.0,
 10690.0,
 10691.0,
 10693.0,
 10694.0,
 10695.0,
 10697.0,
 10698.0,
 10699.0,
 10701.0,
 10702.0,
 10703.0,
 10705.0,
 10706.0,
 10707.0,
 10708.0,
 10709.0,
 10710.0,
 10711.0,
 10713.0,
 10714.0,
 10715.0,
 10717.0,
 10718.0,
 10719.0,
 10721.0,
 10722.0,
 10723.0,
 10725.0,
 10726.0,
 10727.0,
 10729.0,
 10730.0,
 10731.0,
 10733.0,
 10734.0,
 10735.0,
 10736.0,
 10737.0,
 10738.0,
 10739.0,
 10740.0,
 10741.0,
 10742.0,
 10743.0,
 10744.0,
 10745.0,
 10746.0,
 10747.0,
 10748.0,
 10749.0,
 10750.0,
 10751.0,
 10752.0,
 10753.0,
 10754.0,
 10755.0,
 10757.0,
 10758.0,
 10759.0,
 10761.0,
 10762.0,
 10763.0,
 10765.0,
 10766.0,
 10767.0,
 10769.0,
 10770.0,
 10771.0,
 10773.0,
 10774.0,
 10775.0,
 10777.0,
 10778.0,
 10779.0,
 10781.0,
 10782.0,
 10783.0,
 10784.0,
 10785.0,
 10786.0,
 10787.0,
 10788.0,
 10789.0,
 10790.0,
 10791.0,
 10792.0,
 10793.0,
 10794.0,
 10795.0,
 10797.0,
 10798.0,
 10799.0,
 10801.0,
 10802.0,
 10803.0,
 10804.0,
 10805.0,
 10806.0,
 10807.0,
 10809.0,
 10810.0,
 10811.0,
 10813.0,
 10814.0,
 10815.0,
 10816.0,
 10817.0,
 10818.0,
 10819.0,
 10820.0,
 10821.0,
 10822.0,
 10823.0,
 10824.0,
 10825.0,
 10826.0,
 10827.0,
 10829.0,
 10830.0,
 10831.0,
 10833.0,
 10834.0,
 10835.0,
 10837.0,
 10838.0,
 10839.0,
 10841.0,
 10842.0,
 10843.0,
 10844.0,
 10845.0,
 10846.0,
 10847.0,
 10849.0,
 10850.0,
 10851.0,
 10852.0,
 10853.0,
 10854.0,
 10855.0,
 10856.0,
 10857.0,
 10858.0,
 10859.0,
 10860.0,
 10861.0,
 10862.0,
 10863.0,
 10864.0,
 10865.0,
 10866.0,
 10867.0,
 10869.0,
 10870.0,
 10871.0,
 10873.0,
 10874.0,
 10875.0,
 10877.0,
 10878.0,
 10879.0,
 10880.0,
 10881.0,
 10882.0,
 10883.0,
 10884.0,
 10885.0,
 10886.0,
 10887.0,
 10892.0,
 10893.0,
 10894.0,
 10895.0,
 10896.0,
 10897.0,
 10898.0,
 10899.0,
 10900.0,
 10901.0,
 10902.0,
 10903.0,
 10904.0,
 10905.0,
 10906.0,
 10907.0,
 10908.0,
 10909.0,
 10910.0,
 10911.0,
 10913.0,
 10914.0,
 10915.0,
 10924.0,
 10925.0,
 10926.0,
 10927.0,
 10928.0,
 10929.0,
 10930.0,
 10931.0,
 10933.0,
 10934.0,
 10935.0,
 10937.0,
 10938.0,
 10939.0,
 10941.0,
 10942.0,
 10943.0,
 10944.0,
 10945.0,
 10946.0,
 10947.0,
 10948.0,
 10949.0,
 10950.0,
 10951.0,
 10952.0,
 10953.0,
 10954.0,
 10955.0,
 10956.0,
 10957.0,
 10958.0,
 10959.0,
 10960.0,
 10961.0,
 10962.0,
 10963.0,
 10965.0,
 10966.0,
 10967.0,
 10968.0,
 10969.0,
 10970.0,
 10971.0,
 10972.0,
 10973.0,
 10974.0,
 10975.0,
 10976.0,
 10977.0,
 10978.0,
 10979.0,
 10981.0,
 10982.0,
 10983.0,
 10984.0,
 10985.0,
 10986.0,
 10987.0,
 10988.0,
 10989.0,
 10990.0,
 10991.0,
 10993.0,
 10994.0,
 10995.0,
 10996.0,
 10997.0,
 10998.0,
 10999.0,
 11000.0,
 11001.0,
 11002.0,
 11003.0,
 11005.0,
 11006.0,
 11007.0,
 11009.0,
 11010.0,
 11011.0,
 11012.0,
 11013.0,
 11014.0,
 11015.0,
 11017.0,
 11018.0,
 11019.0,
 11021.0,
 11022.0,
 11023.0,
 11024.0,
 11025.0,
 11026.0,
 11027.0,
 11029.0,
 11030.0,
 11031.0,
 11032.0,
 11033.0,
 11034.0,
 11035.0,
 11037.0,
 11038.0,
 11039.0,
 11041.0,
 11042.0,
 11043.0,
 11044.0,
 11045.0,
 11046.0,
 11047.0,
 11049.0,
 11050.0,
 11051.0,
 11052.0,
 11053.0,
 11054.0,
 11055.0,
 11056.0,
 11057.0,
 11058.0,
 11059.0,
 11061.0,
 11062.0,
 11063.0,
 11065.0,
 11066.0,
 11067.0,
 11069.0,
 11070.0,
 11071.0,
 11073.0,
 11074.0,
 11075.0,
 11077.0,
 11078.0,
 11079.0,
 11081.0,
 11082.0,
 11083.0,
 11084.0,
 11085.0,
 11086.0,
 11087.0,
 11088.0,
 11089.0,
 11090.0,
 11091.0,
 11093.0,
 11094.0,
 11095.0,
 11097.0,
 11098.0,
 11099.0,
 11100.0,
 11101.0,
 11102.0,
 11103.0,
 11104.0,
 11105.0,
 11106.0,
 11107.0,
 11108.0,
 11109.0,
 11110.0,
 11111.0,
 11113.0,
 11114.0,
 11115.0,
 11116.0,
 11117.0,
 11118.0,
 11119.0,
 11121.0,
 11122.0,
 11123.0,
 11129.0,
 11130.0,
 11131.0,
 11133.0,
 11134.0,
 11135.0,
 11137.0,
 11138.0,
 11139.0,
 11140.0,
 11141.0,
 11142.0,
 11143.0,
 11149.0,
 11150.0,
 11151.0,
 11152.0,
 11153.0,
 11154.0,
 11155.0,
 11156.0,
 11157.0,
 11158.0,
 11159.0,
 11160.0,
 11161.0,
 11162.0,
 11163.0,
 11165.0,
 11166.0,
 11167.0,
 11168.0,
 11169.0,
 11170.0,
 11171.0,
 11173.0,
 11174.0,
 11175.0,
 11176.0,
 11177.0,
 11178.0,
 11179.0,
 11181.0,
 11182.0,
 11183.0,
 11185.0,
 11186.0,
 11187.0,
 11189.0,
 11190.0,
 11191.0,
 11193.0,
 11194.0,
 11195.0,
 11197.0,
 11198.0,
 11199.0,
 11204.0,
 11205.0,
 ...}

In [34]:
dataset_rhea.RHEA_ID.unique().shape

(5169,)

In [35]:
dataset_rhea.CHEBI_ID.unique().shape

(3262,)

In [23]:
dataset_rhea.uniprot_id.unique().shape

(152869,)

In [1]:
import pandas as pd

dataset_raw_rhea = pd.read_csv("RHEA_enzyme_compound_pairs_sequence_smiles_filtered.csv")
dataset_raw_rhea

,RHEA_ID,EC number,CHEBI_ID,uniprot_id,reaction_SMILES,SMILES,sequence
0,10012.0,1.5.3.6,CHEBI:58413,P08159,O=O.[H]O[H].[H][C@]1(C2=CN=C(O)C=C2)CCC[NH+]1C...,C[NH+]1CCC[C@@H]1c1ccc(O)nc1,MSSKLATPLSIQGEVIYPDDSGFDAIANIWDGRHLQRPSLIARCLS...
1,10016.0,3.1.1.49,CHEBI:16353,Q3ZFI4,COC1=CC(/C=C/C(=O)OCC[N+](C)(C)C)=CC(OC)=C1O.[...,COc1cc(/C=C/C(=O)OCC[N+](C)(C)C)cc(OC)c1O,MASSLKKLITSFLLFFFYTIIVASSEPSCRRYKSIISFGDSIADTG...
2,10028.0,1.4.3.15,CHEBI:29986,A0A499UB99,O=O.[H]O[H].[NH3+][C@H](CCC(=O)[O-])C(=O)[O-]>...,[NH3+][C@H](CCC(=O)[O-])C(=O)[O-],MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...
3,22688.0,1.4.3.19,CHEBI:57416,A0A499UB99,C[C@@H]([NH3+])C(=O)[O-].O=O.[H]O[H]>>CC(=O)C(...,C[C@@H]([NH3+])C(=O)[O-],MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...
4,21816.0,1.4.3.3,CHEBI:59871,A0A499UB99,*[C@@H]([NH3+])C(=O)[O-].O=O.[H]O[H]>>[1*]C(=O...,*[C@@H]([NH3+])C(=O)[O-],MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...
...,...,...,...,...,...,...,...
212278,74515.0,4.2.-.-,CHEBI:193561,P9WEP9,COC1=CC=C([C@@]2(O)C3=C(C=CC(/C=C/C(C)=C/CC4OC...,COc1ccc([C@@]2(O)c3c(ccc(/C=C/C(C)=C/CC4OC4(C)...,MQIVYLFSSVLLTAALAHENGKVAYPFRLFNGTSSVEEISQQDQMD...
212279,74751.0,2.3.1.-,CHEBI:193519,Q4WAY4,*N[C@@H](COP(=O)([O-])OCC(C)(C)[C@@H](O)C(=O)N...,*N[C@@H](COP(=O)([O-])OCC(C)(C)[C@@H](O)C(=O)N...,MNREDVEFPTCDGLILRGWLYPGTIRGPAIVMNQGFNTPKEILLPD...
212280,74751.0,2.3.1.-,CHEBI:324935,Q4WAY4,*N[C@@H](COP(=O)([O-])OCC(C)(C)[C@@H](O)C(=O)N...,CO[C@@H]1[C@H](O)CC[C@]2(CO2)[C@H]1[C@@]1(C)O[...,MNREDVEFPTCDGLILRGWLYPGTIRGPAIVMNQGFNTPKEILLPD...
212281,75895.0,2.3.1.-,CHEBI:194488,F8J3H2,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...,Nc1c2sscc-2[nH]c1=O,MSEKLDSYKLMQEHQTWTSKPASLEEWQIVNEWAIAEKWDLGLGDT...
212282,75895.0,2.3.1.-,CHEBI:142976,F8J3H2,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...,MSEKLDSYKLMQEHQTWTSKPASLEEWQIVNEWAIAEKWDLGLGDT...

In [13]:
dataset_raw_rhea[dataset_raw_rhea["EC number"].isna()]

Empty DataFrame
Columns: [RHEA_ID, EC number, CHEBI_ID, uniprot_id, reaction_SMILES, SMILES, sequence]
Index: []

In [10]:
uniprot = pd.read_csv("swiss_prot_enzymes.csv")
uniprot

,accession,name,sequence,EC
0,P0C9F0,1001R_ASFK5,MVRLFYNPIKYLFYRRSCKKRLRKALKKLNFYHPPKECCQIYRLLE...,NaN
1,P0C9F1,1001R_ASFM2,MVRLFHNPIKCLFYRGSRKTREKKLRKSLKKLNFYHPPGDCCQIYR...,NaN
2,P0C9F2,1001R_ASFP4,MVRLFRNPIKCIFYRRSRKIQEKKLRKSLKKLNFYHPPEDCCQIYR...,NaN
3,P0C9E9,1001R_ASFWA,MVRLFRNPIKCIFYRRSRKIQEKKLRKSLKKLNFYHPPEDCCQIYR...,NaN
4,Q65209,1002L_ASFB7,MGNKESKYLEMCSEEAWLNIPNIFKCIFIRKLFYNKWLKYQEKKLK...,NaN
...,...,...,...,...
571604,Q8ENQ1,ZUPT_OCEIH,MDNMLLAFLLTLFAGLATGVGSLIAFMAKTTNTKFLSFALGLSAGV...,NaN
571605,B5F683,ZUPT_SALA4,MSVPLILTLLAGAATFIGAFLGVLGQKPSNRVLAFSLGFAAGIMLL...,NaN
571606,A9MPX1,ZUPT_SALAR,MSVPLILTLLAGAATFIGAFLGVLGQKPSNRVLAFSLGFAAGIMLL...,NaN
571607,Q57JS2,ZUPT_SALCH,MSVPLILTLLAGAATFIGAFLGVLGQKPSNRVLAFSLGFAAGIMLL...,NaN
571608,B5FV58,ZUPT_SALDC,MSVPLILTLLAGAATFIGAFLGVLGQKPSNRVLAFSLGFAAGIMLL...,NaN

In [3]:
enzymes = uniprot[~uniprot["EC"].isna()]
enzymes.columns = ["uniprot_id", "name", "sequence", "EC number"]
enzymes.drop(["name", "sequence"], inplace=True, axis=1)

/tmp/ipykernel_4167891/3594900589.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  enzymes.drop(["name", "sequence"], inplace=True, axis=1)

In [4]:
enzymes

       uniprot_id EC number
60         Q07262  4.4.1.14
61         Q01912  4.4.1.14
62         B9MGI8  3.5.99.7
63         B9K206  3.5.99.7
64         Q89XR6  3.5.99.7
...           ...       ...
571556     Q99MB4   3.6.5.-
571557     O74310   3.6.5.-
571558     P53729   3.6.5.-
571575     O31688  7.2.2.20
571577     P56725  2.4.2.40

[276193 rows x 2 columns]

In [6]:
dataset = dataset_raw_rhea[dataset_raw_rhea["EC number"].isna()].drop(["EC number"], axis=1)
dataset = pd.merge(dataset, enzymes, on="uniprot_id", how="inner")
dataset

,RHEA_ID,CHEBI_ID,uniprot_id,reaction_SMILES,SMILES,sequence,EC number
0,46988.0,CHEBI:58413,P08159,O=O.[H][C@]1(C2=CN=C(O)C=C2)CCC[NH+]1C>>C[NH+]...,C[NH+]1CCC[C@@H]1c1ccc(O)nc1,MSSKLATPLSIQGEVIYPDDSGFDAIANIWDGRHLQRPSLIARCLS...,1.5.3.6
1,70319.0,CHEBI:58414,O94505,O=P([O-])([O-])O[C@H]1[C@H](O)[C@@H](O)[C@H](O...,O=P([O-])([O-])O[C@H]1[C@H](O)[C@@H](O)[C@H](O...,MSFDAEKQLAIAAVRRASYLTEKVFNQLIKEKSAAGALTKDDKSPV...,3.1.3.7;3.1.3.57
2,70319.0,CHEBI:58414,O95861,O=P([O-])([O-])O[C@H]1[C@H](O)[C@@H](O)[C@H](O...,O=P([O-])([O-])O[C@H]1[C@H](O)[C@@H](O)[C@H](O...,MASSNTVLMRLVASAYSIAQKAGMIVRRVIAEGDLGIVEKTCATDL...,3.1.3.7;3.1.3.57
3,70319.0,CHEBI:58414,Q3ZCK3,O=P([O-])([O-])O[C@H]1[C@H](O)[C@@H](O)[C@H](O...,O=P([O-])([O-])O[C@H]1[C@H](O)[C@@H](O)[C@H](O...,MASSPTVLMRLVASAYSIAQKAGTIVRRVIAEGDLGIIEKTCATDL...,3.1.3.7;3.1.3.57
4,70319.0,CHEBI:58414,Q42546,O=P([O-])([O-])O[C@H]1[C@H](O)[C@@H](O)[C@H](O...,O=P([O-])([O-])O[C@H]1[C@H](O)[C@@H](O)[C@H](O...,MAYEKELDAAKKAASLAARLCQKVQKALLQSDVQSKSDKSPVTVAD...,3.1.3.7;3.1.3.57
...,...,...,...,...,...,...,...
10470,75895.0,CHEBI:194488,F8J3H2,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...,Nc1c2sscc-2[nH]c1=O,MSEKLDSYKLMQEHQTWTSKPASLEEWQIVNEWAIAEKWDLGLGDT...,2.3.1.-
10471,75895.0,CHEBI:142976,F8J3H2,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...,MSEKLDSYKLMQEHQTWTSKPASLEEWQIVNEWAIAEKWDLGLGDT...,2.3.1.-
10472,76255.0,CHEBI:195194,P54098,*O[C@H]1C[C@H](*)O[C@@H]1COP(=O)([O-])O[C@H]1C...,*O[C@H]1C[C@H](*)O[C@@H]1COP(=O)([O-])O[C@H]1C...,MSRLLWRKVAGATVGPGPVPAPGRWVSSSVPASDPSDGQRRRQQQQ...,2.7.7.7;3.1.11.-;4.2.99.-
10473,76255.0,CHEBI:195194,P54099,*O[C@H]1C[C@H](*)O[C@@H]1COP(=O)([O-])O[C@H]1C...,*O[C@H]1C[C@H](*)O[C@@H]1COP(=O)([O-])O[C@H]1C...,MSRLLWKKVAGAKVASGPVPATARWVASSVLDPVPSDGRPPSQMPS...,2.7.7.7;3.1.11.-;4.2.99.-
10474,76255.0,CHEBI:195194,Q9QYV8,*O[C@H]1C[C@H](*)O[C@@H]1COP(=O)([O-])O[C@H]1C...,*O[C@H]1C[C@H](*)O[C@@H]1COP(=O)([O-])O[C@H]1C...,MSRLLWKKVAGAKVASGPVPATGRWVSSSVLDPVPSDGQPQSQMPS...,2.7.7.7;3.1.11.-;4.2.99.-

In [9]:
incomplete_ecs = dataset[(~dataset["EC number"].str.contains(";") & dataset["EC number"].str.contains("-"))]
dataset_raw_rhea = dataset_raw_rhea[~dataset_raw_rhea["EC number"].isna()]
dataset_raw_rhea = pd.concat((dataset_raw_rhea, incomplete_ecs))

,RHEA_ID,EC number,CHEBI_ID,uniprot_id,reaction_SMILES,SMILES,sequence
0,10012.0,1.5.3.6,CHEBI:58413,P08159,O=O.[H]O[H].[H][C@]1(C2=CN=C(O)C=C2)CCC[NH+]1C...,C[NH+]1CCC[C@@H]1c1ccc(O)nc1,MSSKLATPLSIQGEVIYPDDSGFDAIANIWDGRHLQRPSLIARCLS...
2,10016.0,3.1.1.49,CHEBI:16353,Q3ZFI4,COC1=CC(/C=C/C(=O)OCC[N+](C)(C)C)=CC(OC)=C1O.[...,COc1cc(/C=C/C(=O)OCC[N+](C)(C)C)cc(OC)c1O,MASSLKKLITSFLLFFFYTIIVASSEPSCRRYKSIISFGDSIADTG...
3,10028.0,1.4.3.15,CHEBI:29986,A0A499UB99,O=O.[H]O[H].[NH3+][C@H](CCC(=O)[O-])C(=O)[O-]>...,[NH3+][C@H](CCC(=O)[O-])C(=O)[O-],MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...
4,22688.0,1.4.3.19,CHEBI:57416,A0A499UB99,C[C@@H]([NH3+])C(=O)[O-].O=O.[H]O[H]>>CC(=O)C(...,C[C@@H]([NH3+])C(=O)[O-],MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...
5,21816.0,1.4.3.3,CHEBI:59871,A0A499UB99,*[C@@H]([NH3+])C(=O)[O-].O=O.[H]O[H]>>[1*]C(=O...,*[C@@H]([NH3+])C(=O)[O-],MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...
...,...,...,...,...,...,...,...
10467,74515.0,4.2.-.-,CHEBI:193561,P9WEP9,COC1=CC=C([C@@]2(O)C3=C(C=CC(/C=C/C(C)=C/CC4OC...,COc1ccc([C@@]2(O)c3c(ccc(/C=C/C(C)=C/CC4OC4(C)...,MQIVYLFSSVLLTAALAHENGKVAYPFRLFNGTSSVEEISQQDQMD...
10468,74751.0,2.3.1.-,CHEBI:193519,Q4WAY4,*N[C@@H](COP(=O)([O-])OCC(C)(C)[C@@H](O)C(=O)N...,*N[C@@H](COP(=O)([O-])OCC(C)(C)[C@@H](O)C(=O)N...,MNREDVEFPTCDGLILRGWLYPGTIRGPAIVMNQGFNTPKEILLPD...
10469,74751.0,2.3.1.-,CHEBI:324935,Q4WAY4,*N[C@@H](COP(=O)([O-])OCC(C)(C)[C@@H](O)C(=O)N...,CO[C@@H]1[C@H](O)CC[C@]2(CO2)[C@H]1[C@@]1(C)O[...,MNREDVEFPTCDGLILRGWLYPGTIRGPAIVMNQGFNTPKEILLPD...
10470,75895.0,2.3.1.-,CHEBI:194488,F8J3H2,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...,Nc1c2sscc-2[nH]c1=O,MSEKLDSYKLMQEHQTWTSKPASLEEWQIVNEWAIAEKWDLGLGDT...
10471,75895.0,2.3.1.-,CHEBI:142976,F8J3H2,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...,C/C(=C\C(=O)OCCCCCCCC(=O)SCCNC(=O)CCNC(=O)[C@H...,MSEKLDSYKLMQEHQTWTSKPASLEEWQIVNEWAIAEKWDLGLGDT...

In [37]:
dataset_raw_rhea.RHEA_ID.unique().shape

(4978,)

In [38]:
dataset_raw_rhea.CHEBI_ID.unique().shape

(3168,)

In [39]:
dataset_raw_rhea.uniprot_id.unique().shape

(143620,)

In [2]:
dataset_raw_rhea[dataset_raw_rhea["RHEA_ID"] == 23120]

,RHEA_ID,EC number,CHEBI_ID,uniprot_id,reaction_SMILES,SMILES,sequence
37738,23120.0,7.4.2.9,CHEBI:90799,A0A0H2ZGN6,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],MSLLDIKNLSVRFGDTTAVPVVDGLDLSVDKGEVLAIVGESGSGKS...
37739,23120.0,7.4.2.9,CHEBI:90799,A0A0H2ZH52,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],METVLTARDLTRHYEVSRGLFKGHAQVRALNGVSFELEAGKTLAVV...
37740,23120.0,7.4.2.9,CHEBI:90799,A2RI77,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],MAEEKVLEVKNLHVNFHTYAGDVKAIRNVSFDLEKGQTLAIVGESG...
37741,23120.0,7.4.2.9,CHEBI:90799,A2RI78,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],MTEPKKVVEIKNLDLTFNKGKKGANKAINNVSLDIYEGETFGLVGE...
37742,23120.0,7.4.2.9,CHEBI:90799,P0AAG0,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],MALLNVDKLSVHFGDESAPFRAVDRISYSVKQGEVVGIVGESGSGK...
37743,23120.0,7.4.2.9,CHEBI:90799,P0AAG1,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],MALLNVDKLSVHFGDESAPFRAVDRISYSVKQGEVVGIVGESGSGK...
37744,23120.0,7.4.2.9,CHEBI:90799,P0AAG2,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],MALLNVDKLSVHFGDESAPFRAVDRISYSVKQGEVVGIVGESGSGK...
37745,23120.0,7.4.2.9,CHEBI:90799,P26905,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],MEKVLSVQNLHVSFTTYGGTVQAVRGVSFDLYKGETFAIVGESGCG...
37746,23120.0,7.4.2.9,CHEBI:90799,P37313,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],MSTQEATLQQPLLQAIDLKKHYPVKKGMFAPERLVKALDGVSFNLE...
37747,23120.0,7.4.2.9,CHEBI:90799,P45094,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],MTNEVKENTPLLNAIGLKKYYPVKKGLFAKPQQVKALDGVSFQLER...
37748,23120.0,7.4.2.9,CHEBI:90799,P45095,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],MALLDVKELSVHFGDKKTPFKAVDRISYQVAQGEVLGIVGESGSGK...
37749,23120.0,7.4.2.9,CHEBI:90799,Q8RDH4,*C([NH3+])C(=O)NC(*)C(=O)[O-].NC1=NC=NC2=C1N=C...,*C([NH3+])C(=O)NC(*)C(=O)[O-],MSIIIRVEDLRAVYLVREGTIKAADGISLDILENSVTAIVGESASG...

In [2]:
import pandas as pd

final_dataset = pd.read_csv("RHEA_final_dataset_random.csv")

/tmp/ipykernel_2614077/3303559015.py:3: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  final_dataset = pd.read_csv("RHEA_final_dataset_random.csv")

In [9]:
len(final_dataset.CHEBI_ID.unique())

2988

In [12]:
len(final_dataset.uniprot_id.unique())

144541