In [1]:
import pandas as pd


dataset = pd.read_csv("unique_enzymes_curated.fasta.tsv", sep="\t", header=None)
pfam_dataset = dataset[dataset.iloc[:, 3]=="Pfam"]

In [2]:
pfam_dataset = pfam_dataset.iloc[:, [0, 4, 5]]
pfam_dataset.columns = ["uniprot_id", "pfam_id", "description"]

In [3]:
families_to_select = ["Cytochrome P450", "haloacid dehalogenase-like hydrolase", "UDP-glucoronosyl and UDP-glucosyl transferase",
                      "Methyltransferase domain", "Polyprenyl synthetase", "Glycosyl transferase family 2", "Terpene synthase, N-terminal domain",
                      ]

In [4]:
families = {
    "aminotransferase": [],
    "cytochrome p450": [],
    "glycosyl transferase": [],
    "methyltransferase": [],
    "polyprenyl synthase": [],
    "terpene synthase": [],
    "acyltransferase": []
}

for family in pfam_dataset["description"].unique():
    if "aminotransferase" in family.lower():
        families["aminotransferase"].append(family)

    elif "cytochrome p450" in family.lower():
        families["cytochrome p450"].append(family)

    elif "glycosyl transferase" in family.lower():
        families["glycosyl transferase"].append(family)

    elif "udp-glucoronosyl" in family.lower():
        families["glycosyl transferase"].append(family)

    elif "methyltransferase" in family.lower():
        families["methyltransferase"].append(family)

    elif "polyprenyl" in family.lower():
        families["polyprenyl synthase"].append(family)

    elif "terpene" in family.lower():
        families["terpene synthase"].append(family)

    elif "acyltransferase" in family.lower():
        families["acyltransferase"].append(family)

In [5]:
for key, descriptions in families.items():
    pfam_dataset.loc[pfam_dataset['description'].isin(descriptions), 'description'] = key

In [6]:
pfam_dataset.loc[~pfam_dataset['description'].isin(families.keys()), 'description'] = "Other"

In [7]:
pfam_dataset["description"].unique()

array(['Other', 'glycosyl transferase', 'aminotransferase',
       'methyltransferase', 'acyltransferase', 'polyprenyl synthase',
       'cytochrome p450', 'terpene synthase'], dtype=object)

In [8]:
pfam_dataset.drop_duplicates(subset="uniprot_id",inplace=True)

In [9]:
pfam_dataset

       uniprot_id  pfam_id           description
0          Q920P0  PF13561                 Other
16         Q8A9W8  PF13419                 Other
26         O60061  PF00535  glycosyl transferase
38         P18843  PF02540                 Other
39         Q9H6E5  PF00076                 Other
...           ...      ...                   ...
144255     Q6E7F2  PF01370                 Other
144256     Q00909  PF06330                 Other
144270     Q62148  PF00171                 Other
144278   UGT76E11  PF00201  glycosyl transferase
144280     P00946  PF20512                 Other

[10220 rows x 3 columns]

In [ ]:
from plants_sm.io.pickle import read_pickle, write_pickle

_, _, test_dataset = read_pickle("splits_0_4_proteins_train_val_test.pkl")[0]

0                           P00509
2                           P04693
3                       A0A3N0RMA5
15                          C8TYT5
24                      A0A2E1TNK5
                   ...
10264                      UGT72B3
10265                      UGT72B1
10304                         Lb01
10328    Mycolicibacterium_obuense
10361        Virgibacillus_salinus
Name: AC, Length: 2071, dtype: object

In [13]:
pfam_dataset[pfam_dataset["description"]!="Other"][pfam_dataset["uniprot_id"].isin(test_dataset)]

/tmp/ipykernel_3802116/4051005688.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  pfam_dataset[pfam_dataset["description"]!="Other"][pfam_dataset["uniprot_id"].isin(test_dataset)]

       uniprot_id  pfam_id           description
26         O60061  PF00535  glycosyl transferase
2066         Lb01  PF00201  glycosyl transferase
2645       Q9FH76  PF00067       cytochrome p450
3327       F4ZGF2  PF01596     methyltransferase
3649       Q9M8M7  PF00202      aminotransferase
...           ...      ...                   ...
141700     Q9EQK7  PF04140     methyltransferase
142516     Q9SLG2  PF00348   polyprenyl synthase
142602     Q9VK89  PF02005     methyltransferase
143208     P09139  PF00266      aminotransferase
143601     P0A7A5  PF01135     methyltransferase

[208 rows x 3 columns]

In [12]:
pfam_dataset[pfam_dataset["uniprot_id"].isin(test_dataset)]

       uniprot_id  pfam_id           description
16         Q8A9W8  PF13419                 Other
26         O60061  PF00535  glycosyl transferase
39         Q9H6E5  PF00076                 Other
64         Q973W5  PF00501                 Other
198        Q55F68  PF02518                 Other
...           ...      ...                   ...
143937     Q09669  PF25137                 Other
143952     O81027  PF00682                 Other
144035     Q9H3R0  PF13832                 Other
144162     Q8R2F2  PF00487                 Other
144224   KP347730  PF00561                 Other

[2037 rows x 3 columns]