In [1]:
import pandas as pd

dataset = pd.read_csv('augmented_dataset_descriptors_available.csv')

/tmp/ipykernel_2243627/3160751049.py:3: DtypeWarning: Columns (6,8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv('augmented_dataset_descriptors_available.csv')

In [19]:
dataset[dataset.RHEA_ID.isna()].to_csv('augmented_dataset_no_rhea.csv', index=False)

In [18]:
rhea = pd.read_csv('RHEA_final_dataset_random.csv')
rhea

/tmp/ipykernel_2243627/2407577295.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  rhea = pd.read_csv('RHEA_final_dataset_random.csv')

,RHEA_ID,EC number,CHEBI_ID,uniprot_id,reaction_SMILES,SMILES,sequence,interaction
0,RHEA:10012.0,1.5.3.6,CHEBI:58413,P08159,[H][C@]1(C2=CN=C(O)C=C2)CCC[NH+]1C.O=O.[H]O[H]...,C[NH+]1CCC[C@@H]1c1ccc(O)nc1,MSSKLATPLSIQGEVIYPDDSGFDAIANIWDGRHLQRPSLIARCLS...,1
1,RHEA:10028.0,1.4.3.15,CHEBI:29986,A0A499UB99,[NH3+][C@H](CCC(=O)[O-])C(=O)[O-].O=O.[H]O[H]>...,[NH3+][C@H](CCC(=O)[O-])C(=O)[O-],MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...,1
2,RHEA:22688.0,1.4.3.19,CHEBI:57416,A0A499UB99,C[C@@H]([NH3+])C(=O)[O-].O=O.[H]O[H]>>CC(=O)C(...,C[C@@H]([NH3+])C(=O)[O-],MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...,1
3,RHEA:21816.0,1.4.3.3,CHEBI:59871,A0A499UB99,*[C@@H]([NH3+])C(=O)[O-].O=O.[H]O[H]>>[1*]C(=O...,*[C@@H]([NH3+])C(=O)[O-],MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...,1
4,RHEA:37583.0,1.4.3.3,CHEBI:32557,A0A499UB99,[NH3+]CCCC[C@@H]([NH3+])C(=O)[O-].O=O.[H]O[H]>...,[NH3+]CCCC[C@@H]([NH3+])C(=O)[O-],MATNNIVVLGAGVSGLTTAWLLSKDPSNKITVAAKHMPGDYDIEYC...,1
...,...,...,...,...,...,...,...,...
428275,RHEA:fake_58744.0,NaN,CHEBI:87133,Q086I0,C[N+]1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O...,C[n+]1cn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-...,MTTKKRTASSTRWMQEHFDDHYVKLAQKRGLRSRAAFKLEEIQEKD...,0
428276,RHEA:fake_58744.0,NaN,CHEBI:87133,Q0HE54,C[N+]1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O...,C[n+]1cn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-...,MKTPIELKILDSRIGSEFPLPAYATPGSAGMDLRAMIDTTMTIAPG...,0
428277,RHEA:fake_58744.0,NaN,CHEBI:87133,Q99LN9,C[N+]1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O...,C[n+]1cn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-...,MVTEQEIEAIGKTLVDPKQPLQARFRALFTLRGLGGPDAISWISRG...,0
428278,RHEA:fake_58744.0,NaN,CHEBI:87133,B1YHQ8,C[N+]1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O...,C[n+]1cn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-...,MKIMQSVTQLREALAGQTSVGFIPTMGFLHEGHASLLEQARQENDI...,0
428279,RHEA:fake_63644.0,NaN,CHEBI:57273,B7I5C6,*N[C@@H](CO)C(*)=O.C[C@@H]1O[C@H](OP(=O)([O-])...,C[C@@H]1O[C@H](OP(=O)([O-])OP(=O)([O-])OC[C@H]...,MSNSTSTPNTGLSYKDAGVDIEAGDALVDRIKSVAKRTTRPEVMGG...,0

In [19]:
import pandas as pd

dataset = pd.read_csv('augmented_dataset_descriptors_available.csv')
dataset

/tmp/ipykernel_2243627/858493295.py:3: DtypeWarning: Columns (6,8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv('augmented_dataset_descriptors_available.csv')

,Unnamed: 0,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
0,0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
1,1,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 2,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
2,2,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 3,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
3,3,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 4,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
4,4,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 5,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
592388,623398,MAGHHHEHEQERDHEQEHEHDSLQRPTTGSERTRSISFSKLLTRSW...,N[C@@H](CCC([O-])=N[C@@H](CS)C(O)=NCC(=O)O)C(=O)O,0.0,P53739,CHEBI:57925,NaN,False,NaN,NaN,NaN
592389,623399,MAGHHHEHEQERDHEQEHEHDSLQRPTTGSERTRSISFSKLLTRSW...,COC1=C(OC)C(=O)C(CC=C(C)C)=C(C)C1=O,0.0,P53739,CHEBI:16389,NaN,False,NaN,NaN,NaN
592390,623400,MQTSLANIVLFSSLQVLLSLTCFQEVVEAASGKGFGDNIHWRTLDD...,CCCCC[C@H](O)/C=C/[C@@H]1[C@@H](C/C=C\CCCC(=O)...,0.0,H9D1R1,CHEBI:57405,NaN,False,NaN,NaN,NaN
592391,623401,MQTSLANIVLFSSLQVLLSLTCFQEVVEAASGKGFGDNIHWRTLDD...,C[C@]12CC[C@@H]3c4ccc(O)cc4CC[C@H]3[C@@H]1CC[C...,0.0,H9D1R1,CHEBI:16469,NaN,False,NaN,NaN,NaN
592392,623402,MQTSLANIVLFSSLQVLLSLTCFQEVVEAASGKGFGDNIHWRTLDD...,C=C(O[C@@H]1C=C(C(=O)[O-])C=C[C@H]1O)C(=O)[O-],0.0,H9D1R1,CHEBI:29748,NaN,False,NaN,NaN,NaN

In [20]:
rhea_negatives = rhea[rhea.interaction == 0].loc[:, ["SMILES", "uniprot_id", "CHEBI_ID", "sequence", "interaction"]]
rhea_negatives.columns = ["SMILES", "Enzyme ID", "Substrate ID", "Sequence", "Binding"]
rhea_negatives = rhea_negatives[rhea_negatives["Enzyme ID"].isin(dataset.loc[:, "Enzyme ID"])]

In [21]:
dataset = pd.concat([dataset, rhea_negatives], ignore_index=True)
dataset

/home/jcapela/miniforge3/envs/esp/lib/python3.11/site-packages/IPython/lib/pretty.py:786: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  output = repr(obj)
/home/jcapela/miniforge3/envs/esp/lib/python3.11/site-packages/IPython/core/formatters.py:406: FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  return method()

,Unnamed: 0,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
0,0.0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
1,1.0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 2,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
2,2.0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 3,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
3,3.0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 4,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
4,4.0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 5,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
685017,NaN,MDKLLIRGGRALHGEVTVSGAKNAALPELCAALLSSEPVTLRNVPR...,C[n+]1cn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-...,0.0,A9BX80,CHEBI:87133,NaN,NaN,NaN,NaN,NaN
685018,NaN,MIALLIGAGLALLCALVGTPLFIRLLVRRGYGQFIRDDGPTSHHTK...,C[n+]1cn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-...,0.0,B8HGW7,CHEBI:87133,NaN,NaN,NaN,NaN,NaN
685019,NaN,MRKEFLFTSESVTEGHPDKMADQISDAILDYIIERDPKARVACETL...,C[n+]1cn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-...,0.0,Q7M7Z2,CHEBI:87133,NaN,NaN,NaN,NaN,NaN
685020,NaN,MARIVFMGTPDFSVPVLQTLITEGYEVVGVVTQPDRPKGRKRVLTP...,C[n+]1cn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-...,0.0,A8FD38,CHEBI:87133,NaN,NaN,NaN,NaN,NaN
685021,NaN,MKIMQSVTQLREALAGQTSVGFIPTMGFLHEGHASLLEQARQENDI...,C[n+]1cn([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-...,0.0,B1YHQ8,CHEBI:87133,NaN,NaN,NaN,NaN,NaN

In [22]:
dataset.to_csv('augmented_dataset_with_rhea_negatives.csv', index=False)