In [1]:
import pandas as pd

In [2]:
goldman_data = pd.read_csv("../Goldman_data/goldman_data.csv")
kroll_data = pd.read_csv("../kroll_data_experiment/kroll_data.csv")
mou_data = pd.read_csv("../Mou_data/mou_data.csv")
yang_data = pd.read_csv("../Yang_data/yang_training_set_w_sequences.csv")
oat_data = pd.read_csv("../Yang_data/oat_data.csv")
berry_data = pd.read_csv("../Yang_data/berry_data.csv")
robinson_data = pd.read_csv("../Robinson_data/final_dataset.csv")

In [3]:
data = pd.concat([goldman_data, kroll_data, mou_data, yang_data, oat_data, berry_data, robinson_data], axis=0)
data

,Index,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Evidence,Substrate Name,activity,IUPAC
0,0.0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,NaN,NaN,NaN,NaN
1,1.0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 2,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,NaN,NaN,NaN,NaN
2,2.0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 3,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,NaN,NaN,NaN,NaN
3,3.0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 4,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,NaN,NaN,NaN,NaN
4,4.0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 5,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1090,NaN,MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAM...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Pelobacter propionicus,benzoate,https://doi.org/10.1093/synbio/ysaa004,NaN,NaN,NaN,4-nitrophenyl benzoate
1091,NaN,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Bacteroides luti,benzoate,https://doi.org/10.1093/synbio/ysaa004,NaN,NaN,NaN,4-nitrophenyl benzoate
1092,NaN,MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIER...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Nonomuraea candida,benzoate,https://doi.org/10.1093/synbio/ysaa004,NaN,NaN,NaN,4-nitrophenyl benzoate
1093,NaN,MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEAL...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Legionella brunensis,benzoate,https://doi.org/10.1093/synbio/ysaa004,NaN,NaN,NaN,4-nitrophenyl benzoate
1094,NaN,MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTG...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Allokutzneria albata,benzoate,https://doi.org/10.1093/synbio/ysaa004,NaN,NaN,NaN,4-nitrophenyl benzoate

In [4]:
data_cleaned = data.loc[:, ~data.isna().any()]
data_cleaned

,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication
0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
1,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 2,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
2,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 3,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
3,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 4,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
4,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 5,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
...,...,...,...,...,...,...
1090,MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAM...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Pelobacter propionicus,benzoate,https://doi.org/10.1093/synbio/ysaa004
1091,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Bacteroides luti,benzoate,https://doi.org/10.1093/synbio/ysaa004
1092,MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIER...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Nonomuraea candida,benzoate,https://doi.org/10.1093/synbio/ysaa004
1093,MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEAL...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Legionella brunensis,benzoate,https://doi.org/10.1093/synbio/ysaa004
1094,MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTG...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Allokutzneria albata,benzoate,https://doi.org/10.1093/synbio/ysaa004

In [5]:

data_cleaned[data_cleaned.loc[:, "Enzyme ID"].str.contains("phospatase")]

Empty DataFrame
Columns: [Sequence, SMILES, Binding, Enzyme ID, Substrate ID, Publication]
Index: []

In [6]:
data_cleaned[data_cleaned["Binding"] == 1]

,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication
1,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 2,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
3,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 4,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
5,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C1=CC=C(C=C1)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 6,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
6,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C1=CC(=CC=C1C[C@@H](C(=O)O)N)O,1.0,P00509,compound_aminotransferase_dataset 7,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
7,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C1=CC=C2C(=C1)C(=CN2)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 8,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
...,...,...,...,...,...,...
1012,MSGNATYRLSNTTILAACAVEAPIVATSAAFDERLAETYRRVGTRP...,O=[N+](C1=CC=C(OC(C(C)(C)C)=O)C=C1)[O-],1.0,Microlunatus phosphovorus,TMA,https://doi.org/10.1093/synbio/ysaa004
1013,MRSRIKGVGRYLPNRIVTSEEAEELAGFKKLGVRKGLCKMLTGCEE...,O=[N+](C1=CC=C(OC(C(C)(C)C)=O)C=C1)[O-],1.0,Clostridium combesii,TMA,https://doi.org/10.1093/synbio/ysaa004
1014,MLRCAHWHAPALLTANLLDARIERTLLNGRTPGNTTFRHNNAALLG...,O=[N+](C1=CC=C(OC(C(C)(C)C)=O)C=C1)[O-],1.0,Brevibacterium mcbrellneri,TMA,https://doi.org/10.1093/synbio/ysaa004
1016,MVKTMNYIAKLVGVGQALPERVVTSEEMEAMMGFDQLGIRKGMAKI...,O=[N+](C1=CC=C(OC(C(C)(C)C)=O)C=C1)[O-],1.0,Anaerocolumna xylanovorans,TMA,https://doi.org/10.1093/synbio/ysaa004
1018,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,O=[N+](C1=CC=C(OC(C(C)(C)C)=O)C=C1)[O-],1.0,Bacteroides luti,TMA,https://doi.org/10.1093/synbio/ysaa004

In [7]:
data_cleaned[data_cleaned["Binding"] == 0]

,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication
0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
2,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 3,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
4,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 5,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
8,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C([C@@H](C(=O)O)N)O,0.0,P00509,compound_aminotransferase_dataset 9,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
9,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@H]([C@@H](C(=O)O)N)O,0.0,P00509,compound_aminotransferase_dataset 10,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
...,...,...,...,...,...,...
1090,MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAM...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Pelobacter propionicus,benzoate,https://doi.org/10.1093/synbio/ysaa004
1091,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Bacteroides luti,benzoate,https://doi.org/10.1093/synbio/ysaa004
1092,MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIER...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Nonomuraea candida,benzoate,https://doi.org/10.1093/synbio/ysaa004
1093,MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEAL...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Legionella brunensis,benzoate,https://doi.org/10.1093/synbio/ysaa004
1094,MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTG...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Allokutzneria albata,benzoate,https://doi.org/10.1093/synbio/ysaa004

In [8]:
data_cleaned.drop_duplicates(subset=["Enzyme ID", "Substrate ID"], inplace=True)

/tmp/ipykernel_2099242/2141043160.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_cleaned.drop_duplicates(subset=["Enzyme ID", "Substrate ID"], inplace=True)

In [9]:
data_cleaned[data_cleaned["Binding"]==1]

,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication
1,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 2,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
3,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 4,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
5,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C1=CC=C(C=C1)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 6,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
6,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C1=CC(=CC=C1C[C@@H](C(=O)O)N)O,1.0,P00509,compound_aminotransferase_dataset 7,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
7,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C1=CC=C2C(=C1)C(=CN2)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 8,https://pubs.acs.org/doi/10.1021/acscatal.0c01895
...,...,...,...,...,...,...
1012,MSGNATYRLSNTTILAACAVEAPIVATSAAFDERLAETYRRVGTRP...,O=[N+](C1=CC=C(OC(C(C)(C)C)=O)C=C1)[O-],1.0,Microlunatus phosphovorus,TMA,https://doi.org/10.1093/synbio/ysaa004
1013,MRSRIKGVGRYLPNRIVTSEEAEELAGFKKLGVRKGLCKMLTGCEE...,O=[N+](C1=CC=C(OC(C(C)(C)C)=O)C=C1)[O-],1.0,Clostridium combesii,TMA,https://doi.org/10.1093/synbio/ysaa004
1014,MLRCAHWHAPALLTANLLDARIERTLLNGRTPGNTTFRHNNAALLG...,O=[N+](C1=CC=C(OC(C(C)(C)C)=O)C=C1)[O-],1.0,Brevibacterium mcbrellneri,TMA,https://doi.org/10.1093/synbio/ysaa004
1016,MVKTMNYIAKLVGVGQALPERVVTSEEMEAMMGFDQLGIRKGMAKI...,O=[N+](C1=CC=C(OC(C(C)(C)C)=O)C=C1)[O-],1.0,Anaerocolumna xylanovorans,TMA,https://doi.org/10.1093/synbio/ysaa004
1018,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,O=[N+](C1=CC=C(OC(C(C)(C)C)=O)C=C1)[O-],1.0,Bacteroides luti,TMA,https://doi.org/10.1093/synbio/ysaa004

In [10]:
len(data_cleaned["Sequence"].unique())

12423

In [8]:
from rdkit import Chem

smiles = data_cleaned.SMILES.unique()

# Function to generate InChI keys
def generate_inchi_key(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        inchi = Chem.MolToInchi(mol)
        inchi_key = Chem.InchiToInchiKey(inchi)
        return inchi_key
    return None

# Apply the function to the SMILES column
inchikeys = []

for smile in smiles:
    inchi_key = generate_inchi_key(smile)
    inchikeys.append(inchi_key)

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Charges were rearranged

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Charges were rearranged

[18:23:14] WARNING: Charges were rearranged

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed; Omitted undefined stereo

[18:23:14] WARNING: Accepted unusual valence(s): O(1)

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed; Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: not removing hydrogen atom without neighbors
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed; Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed; Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed; Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed; Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed; Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed; Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed; Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed; Omitted undefined stereo

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: not removing hydrogen atom without neighbors
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'

[18:23:14] Invalid InChI prefix in generating InChI Key
[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] WARNING: Proton(s) added/removed

[18:23:14] ERROR: Unsupported in this mode element '*'


In [9]:
# Function to search PubChem using InChI key
import requests
from tqdm import tqdm


def search_pubchem(inchi_key):
    url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/inchikey/{inchi_key}/JSON"
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        return None

pubchem_ids = []
for inchi_key in tqdm(inchikeys):
    info = search_pubchem(inchi_key)
    if info != None:
        cid = info['PC_Compounds'][0]["id"]["id"]["cid"]
        pubchem_ids.append(cid)
    else:
        pubchem_ids.append(None)

  0%|          | 0/1784 [00:00<?, ?it/s]

100%|██████████| 1784/1784 [12:25<00:00,  2.39it/s]

In [15]:
pubchem_ids_df = pd.DataFrame({"SMILES":smiles, "pubchem_id": pubchem_ids})

In [16]:
total = 0
for id_ in pubchem_ids:
    if id_ == None: 
        total+=1
total

109

In [17]:
data_cleaned = pd.merge(data_cleaned, pubchem_ids_df, on="SMILES")

In [22]:
data_cleaned.drop(columns="pubchem_id_y", inplace=True)
data_cleaned = data_cleaned.rename(columns={"pubchem_id_x": "pubchem_id"})

In [23]:
data_cleaned.pubchem_id.value_counts()

5957.0        1904
5461108.0     1697
15938971.0     630
15938972.0     558
7058167.0      462
              ...
91820475.0       1
439733.0         1
90658612.0       1
45266552.0       1
25271619.0       1
Name: pubchem_id, Length: 1638, dtype: int64

In [24]:
data_cleaned.shape

(77665, 7)

In [25]:
data_cleaned.drop_duplicates(subset=["Enzyme ID", "Substrate ID"], keep="first", inplace=True)
data_cleaned.shape

(76471, 7)

In [26]:
data_cleaned.to_csv("integrated_dataset.csv", index=False)