In [32]:
import pandas as pd

In [33]:
from Bio import SeqIO

sequences = {}

# Read the FASTA file
for record in SeqIO.parse("73_OleA_JGI_unaligned.fasta", "fasta"):
    id_ = record.id
    if "Pseudoxanthomonas" in id_:
        id_ = "Pseudoxanthomonas_sp."
    elif "Leifsonia" in id_:
        id_ = "Leifsonia_sp."
    sequence = str(record.seq)

    sequences[id_] = sequence

In [34]:
sequences

{'4KU5_Xanthomonas_campestris': 'MGSSHHHHHHSSGLVPRGSHMLFQNVSIAGLAHIDAPHTLTSKEINERLQPTYDRLGIKTDVLGDVAGIHARRLWDQDVQASDAATQAARKALIDANIGIEKIGLLINTSVSRDYLEPSTASIVSGNLGVSDHCMTFDVANASLAFINGMDIAARMLERGEIDYALVVDGETANLVYEKTLERMTSPDVTEEEFRNELAALTLGCGAAAMVMARSELVPDAPRYKGGVTRSATEWNKLCRGNLDRMVTDTRLLLIEGIKLAQKTFVAAKQVLGWAVEELDQFVIHQVSRPHTAAFVKSFGIDPAKVMTIFGEHGNIGPASVPIVLSKLKELGRLKKGDRIALLGIGSGLNCSMAEVVW',
 'WP_026204600.1_Actinomycetospora_chiangmaiensis': 'MRAAQRYDDVVITGLAHVDAPHVVTSTELEDRLAGTLGRLRITPGLLEKLSGIVERRVWDDGTMPSEVAARAGEKALAASGIDRDDIGILINTSVSRDHLEPSTASIVHGRMELSPEAGNFDLGNACLGFLNGMNVVATMIGAGEIDHGLVVAGETSRFAMESTIARLAGDDATRKMFHQQFATLTVGSGAVAMVLSRGTSGHRFLGGLGRASTMGNSELCVGQADEMRTDSGGLLAAGMELAGRAWKDAVSAFDWDTDSYDVYCLHQVSKVHTRAVADQLGLDIARFPSQFPRFGNIGPAGVPTVLSKAVEDGTVTDGSRVMLMGVGSGINAAAAEVIW',
 'WP_097326105.1_Actinoplanes_atraurantiacus': 'MNVGITGIAYALPAREVTTAELQRRVAPKLPPRMFEQATGITRRRVAADDEYASDLAVDAATKVLADTGRDPLDIDLLLFASATRDMAEPATAHVVQAALGSRAHALDVTNACNSFLNGIDLARSMILAGRARNALVVTGETPTRAMRPSLTSFSQARTALAGYTFGDAGAAVLVEPVATGGILDVDAETHSEHWTVGGIFGGGSRHPRGDEHTYFSGDGRRLRAVFEEIGPGLISRVMNRLDHSWDSYAKVLVHQVTLPYLSRFVEVTGVPQDKLVVTVDELGNMASATLGVQLARTYPDLNPGDRVLLVGLGGGVSLMTMVWEVS',
 'WP_086990725.1_Agrococcus_casei': 'MRGNATTRHSNVALLGITEAVAPVEVSSKSFDDRLADTLKTLRLPKGLLQRVAGVTTRRNWEHPSDYIEGAADAGRRALEEAGVRPDQIGLLINASVSREMLEPSVAVAVHDSIGLSPAAMNFDITNACLGFVNGMTVAASMIDAGQIDYALIIAGEDMSRVQESTVERLRRDGITRDEYLNEFATLTLGSGAAAAVLGRADRHPEGHLIKGGVTRAATWNHGLCIGDYDGMFTDTQGLLDNGMQLISEAWAEAHDNGWEWTTMDHYIPHQISHVHVNALTEATKIDADRVAKTYPELGNVGPASLPITLARKSGEMKQGDRILCLGVGSGLNTAMLEITW',
 'WP_030433686.1_Allokutzneria_albata': 'MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTGVRYRHIAPEDTQASDLAVAAIEKLFASWGHGIDDVDLLIFAAASTDVIEPATAHIVSDKLGGSCPVFDISNACSSVFNAIEVADALIRTGQYRRVLIACGERVSPGARYRDVATMDDFVHAGASHTVSDAGAALLVEASDEPGIIGHRSIANSSAWSATVVPLVHDKESDTLKVEYLGVKTLDLMKGLDQADITPLLDAVAGFGLTMDDFDVVCIHQAVLAYVEVFCERAGIPYDRTVLTLADHGNVASATLPLQLVKAVESGRLNPGDKVLLVGLASGLSLGVMAMQW',
 'WP_084558798.1_Anaerocolumna_xylanovorans': 'MVKTMNYIAKLVGVGQALPERVVTSEEMEAMMGFDQLGIRKGMAKILSGVSERRFASDEINSSDLAVEAAKEAMEMAGKKAEDIDLVIFSALTQDVAEPATANIIMDKLNIRNAKSFDIKNACNAFVCAIEIANMYIKCNDVKNVLIASGEVLSRFVKMDLLKDPAKLKDVNSTFSVGDGGGAIVLERQESEEDFGIITAFRTFPDTWSDGVLWGGGTIYPHDPDKFYFQNESEELMKINFKRAMKFFEEQMEKMKIVREEIDLFIPTQITKYIIIKSSEVLKLPDDRVVSQIGTLGNMSTASIPVALSRAVNSGQLKIGTGQKVVLLGVANGFNVGLVYMSI',
 'WP_090596165.1_Auraticoccus_monumenti': 'MASTATTSLRNAYRLQDTVILSATAVEAPERVTSAWIDEQLSETYSRLSMTPGKFEELAGVVARRWWPSGVSFIDGAAEAGAKALAEAGVEPGQVGLLINTSVSKDHLEPSAAVQVHDAIGLPATCLNFDISNACLGFINGMQVAGTMIDAGQIDYALIVNSENIRGLQEKAIARLQRPETTVAEVREQFATLTLGCGATAMVLGRGDQSSGGHRLLGGTHKSATHHHDLCVGDLSFMRTDTRGLFEAGLALALETFEDSAEEFGWHEVDHLVSHQTSLVHIAALCARLGLDQAKFPLSLPEFGNMGPAAAPFTLATSQDRFEPGDRVMMLGIGSGLNTSFADILW',
 'WP_095301808.1_Bacillus_sp._7586-K': 'MKRNIKITGIGSYLPKRIVDGAEIDKIIGAKNGWSEKKSGVKQRYFVTDETASYMGAEAAKKAIADAGIELNELDCIVSGSGTMEQAIPCNASLIQEQLGLQHSGIPAFDINSTCLSFLTALDMISYAMESGRFNHVLIVSSEIASVGLNWSQNESSILFGDGAVAYVFSKTTETDSSHIIASRMETYSAGAHLSEIRGGGTKIHPRNYAEDTKEDFLFDMDGTAIFKLSYKLLPTFIEKLFKNTNLTMDDIKMIVPHQASASAMKIIRKKLSVNEERFMTIIENYGNMIAASIPMALYEAIKQGRVKRGDKVFLLGTSAGLSIGGILFEY',
 'WP_021267235.1_Bacteriovorax_sp._BAL6_X': 'MKYNNVVIEDYAYIEPPEILTSDKLEELLGPIYTRLKLPHGRLELMTGIKSRGFWPNSTRPSSIATEAGNKLLDKLSKKGIKKGDINLLINSSVCRDFLEPSTASVIHANLEMPSECMLFDISNACLGMVSAWEIVANMIETGAIKRAIILSGENSAPLLDNTIKTLNEDQSITRKSVKKYFANLTIGSAGVAYCLSHKDEAPNAPRITSITNRSDSKANKLCQGDGNPESLVMETDSEELLKYGKALAKKTFDDSGLNPKEIDIVIGHQVGKAHKEVVLGKLGLNKHDTFDTFDTLGNTGSAALPITLAKMNDVKGIEKGKKIALVGIGSGLSCSVLGVTW',
 'WP_073399371.1_Bacteroides_luti': 'MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIKERRIAPREMVCSDYCTIAAEKLMDELKWDKESIDTLVYVSVSRDYIEPNTATVIQGKLGLKSECITFDIPMACSGYCYGLSIVASLLSSGCIKRALLLVGDTPSKIISPLDKTLWPIHGDAGTATALEYNISAKPMYFNLMSDGTQFNAIIAPSSGVREPITIDSLKIIELEPGIARNKTHVAMDGMAVFSFTITSVPKCIKSLCEHFNLDIQDLDYLLLHQANKYIDEKIRKKLKVSEDKVPYCLEYFGNTSSGTIPMTMVTQIREKLSNSQNRMVLCGFGAGLSWASVYIETKDIKVLPLIEY',
 'WP_096166078.1_Brachybacterium_alimentarium': 'MANGNGNTGFVHRNASLLSVEMTLPQVTVTSDEIDEMLSPARKRLRLPKGVLQRVAGVYERRWWRDPQNGWKQGVVLAAERAMAKAGIMRDQVGLLINASVSRQHLEPAVSTGIHHSLGMPSSCMNFDITNACLGFVNAMTMAAGMIDAGQIQYALIVGAEDVEQVQRGTIDRLNAKNSTRADFNNQFASLTLGSGAAAAVIGPTDKHPEGHRLKHTQSRAGTEHHELCVADMQDMRTDSAGLLENGIQLILDTWKGANEDGLDFKSIHHVIPHQVSMVYTRNFSKITGVGMERIPVTFPDWGNVAAEAVPMTLASIQDDVKRGERVLLMGVGSGLNTAMMEVEW',
 'WP_068712879.1_Cephaloticoccus_capnophilus': 'MKFSQTYIESLAAALPDEILTSAEIERRLAPLYERLHLPEGRLELMTGIRERRLWPAGTRASDASARAGRAALAKSCIRPEQIELYIHAAVCRDMLEPATAAFAHRKIGLSPNCQIFDLSNACLGFLNALTLAASMIEAGQIRAALITCGEDSRPLVEQTLRTLNAEPLTRNGIKPYFANLTVGSGAVGAVVCHESLVVPEGLGSGGAAGESSRAHRLIGGVVRAATAHSELCQGETHGADSLAMQTDSEALLIAGVTLAHETWGQFCEETGWDAATPSRFICHQVGSIHRRKLYDTLGIDLAKDFSTFEFLGNTGSVALPATLALAVEKGVVRSGDKVALLGIGSGLNSLMLAVEW',
 'WP_088206054.1_Chlamydiales_bacterium_SCGC_AG-110-P3': 'MEFSNVSVLSAAHIDAPHIVSSQKIESELEPMLTRLGLRPNIISELTGITARRFWDEKTAPSDVATCAAERVLEKAELDRSKIGVIINTSVCKDYIEPSVASLVHGNLKLSSHCINFDIGNACLAFVDAIGIVGNMIERGQVDYALIVDGEGSRFITEETIKRLLDPNCSELEFRSNFASLTLGSGAVAMILCNSKFVDGQHRVISSVTQAATEYNRLCTGQVDKMQTNANTLFKKGLELAHQTMQLAIDKMGWFQKDFAQYIIHQVSENHTSQVAKLFNLDLDKVYKIYRDFGNIGPASIPIAFSKALDEGCIKEGDRVGVMGIGSGINVTMMEILW',
 'WP_099839552.1_Clostridium_combesii': 'MRSRIKGVGRYLPNRIVTSEEAEELAGFKKLGVRKGLCKMLTGCEERRYSDTNEYSSHIAAKAAIDAMKKAGVSSDEVDALIFCSVSQDFAEPATANVVMDLLNIKNAFGFDVKNACNAFLTGIDIADSLIKTGKADIVLVVSGEALSKWINFKFESKEELIRRAPVTLSIGDGGGAFIMGREEDDNKGIVKGIFRTYAEYWNNNVVWGGGVRFPRDSDKMYIPGTTKVIIDEQRNLGKNLLPILEREVGWNFQKDVDCYIPTQVAKWINKSMSNELSFPIEKIIQVVDKFGNVGASNIPIATYEAIMDGRLKTGSKTLMSGVGVGINIATIAVIL',
 'WP_020589018.1_Desulfobacter_curvatus': 'MKYDKVFIESFGYELAPHIVTSQEIDEKLAPFFEAVGFVPGQLEALTGIRERRYWDEDHTIAEHAAVAGKRALDEAGISPKELGALCFCGVCQDGFEPATSCAVADMIGVGPRAHVYDVKSACLGMITGMVHVANEIQLGHIKAGLVVSCESARQIVDATIEEINTHKSIDFYREAVATMTGGSGAAAILLTDGTLGKPSTQRHAVKGGVVNNAIRHWNLCSWGFEDKGMPTDSRVIMRTNAQKVLDHGVELVVETYEMFRKEFNLSADQPDKIVGHQVGEGHHNRFYTAMNIDRKKDFSTFPFLGNVGSVSLPISAAIADERGFFVPGDFVVFVGVGSGLNCYFLGVEW',
 'WP_051554118.1_Desulfobulbus_elongatus': 'MNLRYSRVCLHEFGYQLPPVELSSTTIEERLGPLYERLKLPAGRLELMTGIAARRLWQPGTRPSAGAAAAGAAAIARAGIDVAELECLLFTSVSRDMMEPATAAFVHRALGLPPDCLLFDISNACLGFLDGMVMLANMLEMGQVRAGLVVAGETAENLIDSTLAHLLADTTLTRKTIKPLFASLTIGSGAVALVMSRSDCRDTGHYLRGGACRANTAHNDLCQGGQNAEQGTLMSTDSEQLLEKGIETAAACWRSFQTALGWDKGAIDRFFCHQVGKAHAQMLFETLQLDPARNFETLPTLGNVGSVSAPITMALGIEQGALVPGQRAAILGIGSGINALMLGIDW',
 'WP_088919872.1_Granulosicoccus_antarcticus': 'MKGCAVSNNFQYQFNDVAIVSIEACDAPVVVTSAAIDEALAPFLERVGAETGLLQKLAGIEERRQWPDDISFIEASALAGEKAIAASGIDPSRIGMISNTSVCRDRLEPSSAVSVHDRLGLSPHCINFDLSNACLGFVNAMHLAGTLIESGQIEYALIVDGEGTREIQQNTINRLLDEHSSMADLFSNFASLTLGSGSAAMILGRHSTNPGSHRLGRGEFRAATEHHDLCVGSLESMRTDTRALLEAGTQLGKICWDQADSDDWGDMDRYIIHQVSRVHTAAMVEILGIDHKRVPLTFPKYGNIGPAAVPFTLAKEAETLNEGDRVLLVGVGSGLNAAFLEITW',
 'WP_026862459.1_Intrasporangiaceae_bacterium_URHB0013': 'MSGNATYRHTQAAVLSICAVDAPVVVTSDEMDQRLLTTYQRVGLKPGMLARLAGIHERRWWPEGVSFTEGAAIAGGKALAEAGVDPSRVGLMVNTSVSREHLEPSMAVQIHHALGMPTSCLNFDLANACLGFVNGMQLAATMIDSGQIDYALIVDGESSRHTQEVTLDRLSSPDATVDDVLSQFATLTLGSGAAAMVLGRADLHPQGHRIVGGVARAGTEHHDLCVGDLEWMRTDTRGLLEAGIALSRAAWQDARAEFDWSDMDRYIAHQISQVHVRAMCDALDIPPERLPLTFPTRGNMGPASVAFTLAMEADSLAAGDRVLMMGVGSGLNVSCLEIAW',
 'WP_013837355.1_Isoptericola_variabilis': 'MDGNATTRFSNVSLLAVTRRLPSRVTTSAEIQGLLAPALRRLRVPGRLLERVAGVHARRSWGPDEDCDAATVAAAQEALDRAGVAPDDVGLLVNTSVTRKHLEPSVAVALHHGLGLPSSAVNFDVANACLGFINGMSIAAGMIESGQIRYALVVDGEDADEVRATTVERLLRDGVGREDFMQEFATLTLGSGSATAVLGRADEHPEGHRLLGGVTRAATRFHDLCVGSAKGMFTDARALLDGGLELVVDAWKEAVSEWDWASMDRYVTHQVSRVHTDAIVEAVGLDRSKVPTTFPRLGNVGPASVPITLAEEAETLRRGDRVLLMGVGSGINTAMMELAW',
 'WP_076585679.1_Luteimonas_tolerans': 'MLFKNVAIAGLAHVDAPHSLTSDEINLRLKPTLDRLGIRVDVLKDIAGIHARRLWGSDKLASDAATEAGILALKDAGIQSGQLGLLVSTSVSRDYLEPSTASIVAGNLQVGDTCQNYDVANACLAFINGMDMAARMIERGEIDYALVVDGETADLAYEKTIERMLRPDSTEDEFRNELATLTLGSGAAGMVLARAELHPEAPRYKGGVTRSATEWNTLCRGNLDRMVTDTKQLLVQGMNLAGKTFVAAKQAMGWAVHELDQFVVHQVSKVHTQTLIQKFGIDPKKVMTIFGEHGNIGPASVPIVLSKLKQAGRLKKGDRIALLGIGSGLNCTMSEVVW',
 'WP_076469753.1_Micromonospora_avicenniae': 'MVHTRTADASPATRVGITAAAAALPERVVTSAELQEQVERESGITLPPRLFSRMTGIDTRRVAGPEEHASTLAVRAARAVLGSAAADPDDVDLLIFASASRDMAEPATAHIVQADLGTRAHVFDLTNACNSFLNGIDTARAFILAGRARRVLVVTGETPTRSMRMRASSAAQVRSAFAGYTFGDAGAAVLVEQVPTGGILDVQTATFSEHWTAGGIDGGGSRHPRGDEHTYFHGDGGKLRSIFERIGLDVLRAVHHRTGLDWSDYEKVLVHQVTLPYLTRFMELARVPEEKLIVTVPELGNVASATIGVQLARINEKLASGSRVFCLGLGGGVSITTMVWEKS',
 'WP_040156198.1_Mobilicoccus_massiliensis': 'MSENASYRLANCSILSVSTVEAPEVVTSDHLDELLQPAYDTTGMMAGQIERLAGVRERRWFPKDADYTRGAVEAGRQAIADARIDADRIGLIVNASVTRPHLEPGISAMVHAELELPRSCIAFDVTNACLGVVNSLQIAGTMIDAGQIEYALIVASEGARQMQEASIARLVDGGSRQDVKDAFATMTLGSGAVGIVLGRSDRHPEGHQIIGGITRAGTEHHELCIGGMDGMRTDASKLFVEGLSLATDAWAEAKGEWDWEEMDWYVAHQTSTAHIACLCDTLKLPAEKFPVTVDTYGNIGPVALPFTLGMYQHKMRKGDRVLLMGIGSGLNTSMTEVRW',
 'WP_082133371.1_Mycolicibacterium_obuense': 'MTLPTLYFSRPATVLPDTAMDNDEVLALVRKEFSGPAEEWIGVEQTIRYVFDRCNTKTRYLDQSTTLMPAEFATQAAQACLERTGVSATDLDLVVYGGIARGNFEPATAAEVAGLLGARPLHAVDVTCACAGLIEAMHTVAGYFALHPEMKTALVCAGELTRDRIAYDMGSLQDVAVFAAGLTLGNAAAAMVVSREPLPGGSARLEGIFHKTLCEHYDLCKTPIDGHFTSKSKELFALSVHVPPAIREMLGELGWSSEEIDHYALHQPSEAVLERVFTELGARPQACVHTHSLFGNTASTAWALALEYRLEHGTVEPGDKIVMASAAAGFTIVGAAAVWEG',
 'WP_063765283.1_Nonomuraea_candida': 'MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIERLSGVRRRHVAPPGVLPSDLAVAAARDVLRQTGHAPPAIDLIIYAGVSADAVEPATGHMVAAKLGADCPVFDVRNACNSVLNAIEVADLFITSGRHRTVLIACGEVITAAMPWRLASEEEFTTAVPSYTVSDSGSALLLQAADAPGVLGHRFCANSADWEVSAMPFVRDGAGALRVGAFTIDSVGLAIGVQKLDREIWRRPLAEHGLDWDDMAAICVHQPSLAALGAVCELAGIPRDKAEVTIADHGNLAASTIPMQLHLATEAGRVRRGDLVALVGVASGISAGTVLLRW',
 'WP_090922125.1_Paenibacillus_polysaccharolyticus': 'MQLRRVRIAGTGKYLPQMKVTDEELDERLHVPAGWVSKATGVGYRYYASDEETSSYMGARAAEAALADAGLSFGEIDCLVCTSGTKEQPLPSTAVFIQQAMGQEESGVPAFDMDATCLSFLNGLDVISYMVDAGRYQRVLLVATEIASAGLNWKDPESAALFGDGAAAVIIERASEESGSQIVHASLRTYSRGARFSEIAGGGTRHHAAQYDVAHPDPFLFHMDGQAIFRMASKLLPGFMNEMLQASGDRMEDFSLVIPHQGSAMAMRLIRKKLGIPAERFMDITQGHGNTIAASIPMGLHEAIRQQRIERGDRVLMIGTAAGLSLGGLIFDY',
 'WP_028865527.1_Psychromonas_aquimarina': 'MKYSRVFINSLAYELAPHAVSSSELESRLAPLYQKLRIPMGQLAALTGIQERRWWPSDHRLSDGAIEAAKKTIDETGVNINDVGAVVYTGVCRDQHEPATACRIAAELGVNNSTAIYDISNACLGVLSGMLDIANRIELGQIKAGLVVSCESARHIVDITIDNMLENQTIQNFSQSLATLTGGSGAVAVLLTDGSLPLKNSRQHKLLGASHLSAPEHNDLCKWGLQEVGLKLHREFMRTNAVPLLKEGVALALDTWKHFLSQRNWVNEQVDKVICHQVGSANQKQVLAALNIPAHKEFPTFQKLGNMGTVSLPVTAAMAHDQGFLKKGDNVSFLGIGSGLNCMMLGLEW',
 'WP_015101236.1_Saccharothrix_espanaensis': 'MGTQLAGVAVHLPEQQVSTTEVERRLAPFTPPAGLIHRLTGVESRHVMGEHEQASDLAVAAARKLLAETGTAAADVDLLLFASASQDMVEPATAHIVAAKLELRCPVMDVKNACNSVLNGIEVADALIASGRYRTVLVASGEAPSRAVRWQVGGLAEFLRAFPGYTLSDAGAALLLTRGEEGVLGCGFTADSSRWDVGTLPGGGSRYPRDPERTYFDMDGARLKDAFLGLGRGVLDSTLDRLGLTWDDFAVIGVHQVSLPYLDMFARQVGVPTDRLVITLPQHGNVASASLPLQLVTARQLGRCGPGDLVALVGLAGGVSLGLVVIRL',
 'WP_092493676.1_Virgibacillus_salinus': 'MNVGLLGTGHYVPTNVVTNKDMEKIVDTNDEWIRTRTGIEERRIASDDINTSDMAFFAAQEALKESNVKAEDIDLILVATVTPDTPFPSVSCMIQDRLGARKAAAMDISAACSGFMYGVVTAKQFIETNAYKNILVVGAEKLSKITDWSDRNTCVLFGDGAGAAVVGPVSEGKGILSFELGADGSGGKELYQNDEDHLMMNGREVFKFAVRQMPDSSVNVVEQAGYNKEDVDYLVPHQANIRIMEAAREKLGISEEKMATSIKRYGNNSSASIPIALSEGVKSGKIKDDDLVVLVGFGGGLTWGAIALRWGK',
 'WP_044441590.1_Agreia_bicolorata': 'MDGNATTTHRNVALLSVATTMATRITTSAEIDRRLAPSLKRLKLPTGLLQRVAGVHERRNWGEGQTFDDAAIEAGKKALAEAGIRPDQVGLLINTSVTRKHLEPSVAVRIHHGLGLPSSATNFDIANACLGFVNGMALAGQLIDAGQIDYAVIIDGEDADEIQVNTIERLGREGIKRKDFMSEFASLTLGSGAAAAVIGRADLHPEGHRMLGGITRAATQFNDLCVGSVDGMFTDAKALLKGGMELVVSAWKDAKRQWSWSHMDRYIMHQVSSVHTNAIVKAANLDATRVPVTFPLLGNVGPASIPITLAQEASKLVRGNRVLLMGVGSGLNTSMMEIAW',
 'WP_003805730.1_Arthrobacter_globiformis': 'MQDGNEQGLDLAGNATFRHSNTALLSVSSVEAPRIVSSTDFDRRLASTLQRLKFPPRLLERVAGITHRRWWAAGTSFDDAAVEAGAKALAEAGVEASDIGLLINTSVTRRNLEPSVAVKIHHGLSLPSSAMNFDLANACLGFVNGMTLAANMIDSGQIKYAMIVNGEDAQATQEATLARLQRPETTREDFNREFATLTLGSGAAAAVLGPADQHPGAHRILGGVMRAGTEHHELCVGGIDGMATDTKGLLDGGLRLVVDAWNEAQPEWDWASMDRYITHQVSTAYTQAIIGAIDLDPDRVPITFPHWGNVGPASLPMTLAAEAQTLGTGDRVLCMGVGSGLNTAMVEIVW',
 'WP_005885358.1_Brevibacterium_mcbrellneri': 'MLRCAHWHAPALLTANLLDARIERTLLNGRTPGNTTFRHNNAALLGIAETTAPNPVSSGSFDEKLASTLKRLHLPQGLIRRVAGVDYRRNWDNPHDFIAGAVNAGKQALERAQVDADQIGVMINTSVTRETLEPSVAVSIHHGIGLPTSAMNFDIANACLGFVNGMTVVSTMIDSGQIDYGLVVAGEDATRVQQATLNRLSQDDITRAEYLNEFASLTLGCGAAAAVLGPADRHPEGHRILGGVTRAGTWNHELCVGDHNGMFTDATGLLTNGMELVINAWNEAHEDGWDWNDMTMYVTHQVSKIHTNEMAKTASLDLDRMPVTFPELGNVGPASLPITLARNADSLKSGDRILAMGVGSGLNTAMTEIVW',
 'WP_034630949.1_Cellulomonas_cellasea': 'MSGNATSRHRNAALLALASTTPDRVTTSADIDRRLAPALKRLRLPRGLLQRVAGVHERRNWADGQTFDGAAIAAAEKALAESGIDRREVGLLVNTSVTRKHLEPSVAVRIHHGLGLPSSAVNFDIANACLGFVNGMNLAAQLIDAGQIKYAVVVAGEDADDIQNNTIERLIGDDITRADFMQEFASLTLGSGAAAAVVGPADAHPEGHRILGGVTRAATQFHDVCVGSVEGMYTDTRALLEGGMELVLAAWTEARHEWDWAAMDRYILHQVSDVHTKAIVKAAGLDRSRIPTTYGRYGNVGPASIPITLAHEASSLEPGDRLLLMGVGSGLNTAMMEIAW',
 'WP_015490789.1_Clavibacter_michiganensis': 'MLLNGNATFRHRNTSLLGLASVLAPHTVTSVEIDDRLKPVLSRLRLPTGLLQRVAGVLERRNWDTSMSFDAAATEAGRTALAQAGVQPSQIGLLINTSVTRAHLEPSVAVSIHNGLGLPSSALNFDIANACLGFVNAMTLAGHLIDSGQIDYAMIVDGEDAGEIRHNTVARLLRPETTRADFLSEFPSLTLGAGAAAAVLGRTSDHPEGHRILGGVTRAATQHHELCIGDVDGMFTDTKELLRGGMELVVDAWKEAAQDDWEWSDMDRYILHQVSDVHTNAIVKAAKLDKSRVPLTYPRYGNVGPASIPITLADQADSLSRGDRVLCMGVGSGLNTAMTEILW',
 'WP_028327376.1_Dermatophilus_congolensis': 'MSGNASYHLSNCSILAVTTVEAPEIVTSAELDTALAPAYTETRTVAGQLERLAGVKQRRWFPADEDFTDGAVEAGRRALHTAGISPEQVGLVINASVTRPHLEPGISAKVHAELGLPRNCMDFDVTNACLGVVNGMQIAGTMIDAGQIRYGLIVASESSRQMQEATIKRLNAGGATKSDVKQAFATMTLGSGAVAILIGPTDAHPEGHRLLGGITRAGTEHHRLCVGSMDGMRTEASKLFREGIDLALDAYTESAEDGWDWKDMDWYVAHQTSTAHIATLAQRLGKPLEKFPTTISEYGNIGPAAMPYTLGTFQDQFATGDRLLLMGIGSGLNASFVEVQW',
 'WP_012948569.1_Geodermatophilus_obscurus': 'MSGNATHRFGNTAVLALQTTDATRVVTSDALDDALADTYRRVGLRPGLLERLAGIRERRWWGEGVTFVDGAAEAGAKAISESGVDPAGIGVMINTSVSRRWLEPSTAVAVHHALGLPRSCQNFDVTNACLGFVNGMELAAAMIDAGLVEHALVVNGEDAQPVQERTLDRLNQPGTGSKDVIAQFATLTLGSGAAAMVLGRADRHPEGHRLVASVSRAGTEHHELCVGDNDLMRTDLKGLLDAGLALSEDMWADAAAEVDWAGGMSRYIVHQVSKVHTQAMCDRFSIDPALVPTTFPTRGNLGPASVPYTLAGEQDSLVDGDRVLLMGIGSGLNVSCLELAW',
 'WP_006592558.1_Kineosphaera_limosa': 'MSENATYRLANTTILSVSALEAPQVVSSAELDESLAPAYARHGVKAGQIERLAGVVQRRWYPPEADYTDGAVDVGRAAMADAGVEAGEIGLVINASVTRPYLEPGISARVHHELGLPRRAIAFDLTNACLGVANAMHVAGTMIDAGQIDNALIVASEGSRQMQESSIKYLLSDDSTREDVKEAFATMTLGSGAVGLVLGRSDARPDGHRVIGGVTRAGSEHHTLCVGGMDGMRTDSSRLFREGLTLATEAWKDARGDFDWDDMDWYVAHQTSTIHIEALCKTLGLPQERFPMTLPTYGNIGPVAMPYTLAFHQDNIERGQRVLLMGIGSGLNTSMTEVAW',
 'WP_012802190.1_Kytococcus_sedentarius': 'MPGNATFRHSNTSVLSVTALPAPEVHTSAEFDARIMDTLRRNKLVPGVLSRLVGIKERRWWPEDVHFTEAAAEAGRRALVDAGIKPEQVGLMVNTSVSRDHLEPSTAVRIHDTLGLPRSASNFDVTNACLGFVNGMQIAAAMIDSGQIEYALIVNAETTRHTHETTLKRLESEDATADDVLQQLATLTLGSGAAAMVLGRTDKHPEGHRFVGGVSRAGTEHHELCVGDFDRMTTDSVGLQEAGIALSEELWAEAAEEFDWQHLDRYVIHQVSTVHTEQICDRLGLDGAKVPRTFPTYGNMGPAAVPFTLALEAPHLERGDRVLLMGIGSGLNACCAEIEW',
 'WP_058441655.1_Legionella_brunensis': 'MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEALTKIHQRRYWPVDHQLSDHAALAAKKAIKESGINSKKIQVLIYAGVGRAQLEPATACAVAHQLAIASDASVYDVSNACLGVLNGIIQIANAIELGQIHAGLVVSAESCREIIDTMVAEMKIQRNIEHFALSLATLTGGSGAVAVLLSDNALDSSHQLLGAVARQKSQWHQLCRWGSKTGILGNACNIMHTDSVSVLKYGVELGVETYKDFLQELLWQDSFPDKYICHQVGEANQLAIRRALNIPKERDFTTYETLANTGTVALPMTAAIADQVGFLKTGDKVAFLGIGSGLNCMMLGIKW',
 'WP_013865923.1_Microlunatus_phosphovorus': 'MSGNATYRLSNTTILAACAVEAPIVATSAAFDERLAETYRRVGTRPGLLVRLAGVQERRWWPEDVTFADAAAMAGAKALAEAGIRPEQVGVVINTSVCRSHLEPSVAVAVHHQLGLPTNCLNFDVANACLGFVNAIQLAGTLIDSGQLDYALIVDAEGSRQIHELTLDRLSSPTATAAEFKEQFASLTIGSGSAAFVLGRADRHPEGHRVIGGASRTGSEHHDLCVGSLDMMRTDSKKLFDHGIALAVATWEDAKDEFDWDGAVDWFIAHQTSTVHLRAMAKAVGVSSAHFPTTVEKYGNMGPAAVPFTLAHHADRMRAGDRIVLIGIGSGLNTSFAEIVW',
 'WP_091632192.1_Micromonospora_peucetia': 'MTHGNAEYRYTNTAILSVAALEAPVIVTSDQFDEQLSETFRRLRLRRGMLQRIAGIQERRWWPEGFGFADAAAMAGAKALSEAGVDARDVGLLINTSVSRAHLEPSTAVAIHHSLELPPSALNFDIANACLGFVNGIQVAANMIDAGQIRYALIVAGESSREAQQATIERLRSFDSTLDDVREQFATLTLGSGAAAMVLATADAHKQGHRLVGGVGRAATQHHDLCVGDNTRMRTDAKGLLDAGLDLAEATWAHAGSWDWQNMDLYVMHQVSVAHTHGVVNRLGLDTRKVPETFPLLGNVGPASLPLTLAHHAESLNSGDRVLCMGVGSGLNTCALEVVW',
 'WP_015749354.1_Nakamurella_multipartita': 'MTGNSDFRFHDVAILSLDAGPAPLVVTSADVDRRLAPFYARTRSMSGLVTSLAGDFERRQWPAEVSFIQAAARAGEAAIAAAGIDRARIGVVIDTSVSRARLEPSSAVSVHHLLDLPPNCLNFDVSNACLGFVTGLHLAGALIDSGQIDYALIVDGEGTREIYDRTIDRLNERGEGLPDLLANFATFTLGSGAAAMVLGRHSAHPEGHQLLDGFFRAETRHHELCIGTIDGGVTDSRALLEAGIELAGAAWAQAGATAAWGSRDRYIFHQVSEVHTKAMIRTLGVDPAKVPTTFARYGNIGPAAIPITLATVADELSPGDIVLCMGIGSGLNVGVIELRW',
 'WP_079726385.1_Okibacterium_fritillariae': 'MDGNATTTHSNVALLSVATTIAPRITTSEDIDSRLQPVLKKLKLPQGLLQRVAGVLERRNWDEGQNFDDAAVEAGKKALAEAGIEPSQIGLIINTSVTRKHLEPSVAVRIHNGLGLPSSAINFDIANACLGFVNGMSLAAQLIESGQIKYAMIVDGEDADEIQVNTIERLSKGGIGRKEFMSEFASLTLGSGAAAAVIGPADLHPEGHRILGGVTRAATQFNELCVGSVDGMFTDAKALLKGGMELVVSAWKEAKRDWNWSSMDRYILHQVSEVHTNAIVKAAHIDRSKVPVTYPHYGNVGPASIPITLEAEKETLKKGDRVLLMGVGSGLNTAMMEIAW',
 'WP_005508112.1_Rothia_mucilaginosa': 'MLNASADKVGTNSDIRHANAALLSITHELPPDVVTSDYFDEQLAQTYKRLRMPKGLLERLAGISTRRGWAEGQTFEDGVVAAAEKAIAEAGIDRSQIGLLINASVTRDNFEPAVSVGVHDRLELPRHALNFDITNACLGFVNAMTVASTMIDAGAIDYALIVAGEDPSPWHRTAVRILNNPDSTREDVLAQFATLTLGSGAAAAVIGRADRHPEGHRIVGSVSRAGTEHRNLCIGGEADQGMNTDAEGLLKHGLELVAQAWEQAHQDGWEWNDMTSYVTHQISNAHTNAIIEAVGIERERIPLTFPKWGNVAAAALPMTLAECAPTYTEGDRILCMGVGSGLNTALLEIQW',
 'WP_012868615.1_Sanguibacter_keddieii': 'MNGNATSKHQNVALLSVATVVPDVVTTSDEMDNRLADTLKRLRMPRGLLQRVAGVHERRRWAADQSFESAAIAAGEKALAEAGISASDIGLIINTSVTRPHLEPSVAVRMHHGLGLPSSAMNFDIANACLGFINGMNVAAHMIDSGQIRYAMIIDGEDADEVNDNTIDRLNRPETKRSDFMNEFASLTLGSGAAAAILGPADSHPSGHRILGGVTRAATQFHDVCVGSVNGMYTDTKALLKGGMELVVAAWQEAKESWSWTAMDRYVMHQVSDVHTSAIVKAAKLDRSKVPTTYPRYGNVGPASIPITLAEQSSTLAPGDRVLLMGVGSGLNTSMMEITW',
 'WP_061782733.1_Shewanella_putrefaciens': 'MKYSRVFINSLAYELALVVVSSSELESRLAPLYQKFRIPMGQLAALTGITERRWWPKGHQLSDGAINAARKAIAETGINVADLGVVVYTGVCRDQHEPATACRIAAELGVSKDTAIYDISNACLGVLSGILDIANRIELGQIKAGMVVSCESARDIVDVTIDNMLASPTMQNFAQSLATLAGGSGAVAVILTDGSLPLTNVRKHQLLGASHLSAPEHHQLCQWGLQEVGHNLYREFMRTDAVTLLKEGVELAKHTWEHFLEQRNWLVEQVDKVICHQVGASNRKQVLSALNIPPEKEFPTYQLLGNMGTVSLPVTAAMAHDEGFLQAGDQVSFLGIGSGLNCMMLGIKW',
 'CVN04163.1_Streptococcus_pneumoniae': 'MSAPSPTPRRLVLVTNVSGNASYEYSRAALLAVTEVEAPVEVTSQDLDDQLAEVLTRLRLPGSLLERVAGVRSRRNWDETEDFQEAAARAGVAALEQAGVPRERVGLLVNTSVTRATLEPSVAVRIHHLMGLPTSATNFDITNACLGFVNGLMLASTLVDAGQIDYAVVVAAEDASKVQAATVANLHAETTHRGNFMEQFASLTLGSGAAAAVVGRIEDHPDAHRIVRGITRAGTDHHGLCVGDHHGMYTDSTALLKDGLELVMDAWHDVPAEWAWPEADRFITHQVSQMHTDAIAESAHLDPARIPTTFPTLGNVGPASLPITLVREMDALEDGDTVVCLGVGSGLNTAMLEIEW',
 'WP_053141838.1_Streptomyces_ambofaciens': 'MSEAIRARIAAVCAHLPSRYRTLDETRAKITETGGYAPPPGLLEDLTGVRGVHVHEDGENSSDLAVAAARSALEQAGLKIRDVDLLLFASTSQDLIEPATAHLVATKLGASCPVFDVKNACNSFLNGMEVAASFIETGRYRTVLIACGEPATLATRWHLPTREDLLRALPGYTASDAGAAMVLTAGPAGDGDPGILSLRFVSNSPAWEACTVAGGGSMHHLSVHDDHTTLRLNGDLWQSALDVLPRIMDTAGEEFRAAQAGAVSFIAFHQIAMPQYREVIDLFSLPEDRCMPAVAEHGNCAAASLPLQLAKAREADRIEGGDLVAMIGLASGFSFGLALVRW',
 'WP_010983715.1_Streptomyces_avermitilis': 'MRFENDLYIASTASWLPDLVPMEEAIAAGLVDDEHRNLGYESIAVADGVAGPEMAVRAGRLALERAVGIERDEVGLVLHSSCGFQGHEMWPAAAYVANETVGRAAPGFDLQQRCNAGLGSLCLAAGYIDAGFTSAVLLTTGDNFAPPWVDRWNVQLNLVFADGGTALVLSGRKGFARVVSATLGADNSLERWNRGTTPFATAPGLEMPLRLRERGLQHAATPEAEGSWERIEAALMDTTRRALAEAQVSVEDISRVVTPLIHRGVWPENYDVLGFTEKQSTWDLGRLVGHIGAGDQFLGLEHLVKERAVGPGDLVLLVAAGAGFSLSAAVVEILDVPPW',
 'WP_068469535.1_Kocuria_varians_strain_G6': 'MTGNSTITNRNVAILSVTKTEADVVIPSTRFDEELAETFRRLRMPKGLLERLAGIKERRGWAPGRHFTDGATEAGEAALAESGVRPEQIGLFVNASVTRDNYEPAVAVGIHERLGLPSSALNFDMTNACLGFVNALTVAASMIDAGAIEYALVVAGEDPSPWHKAAVERLRADDITREQVVQEFATLTLGCGAAAAVVGPADRHPDGHRIVGSVTRAGTEFNHLCIGGDDGMFTDATGLLNHGVGLVVEAWHEAEQDGWDWREMDSYVTHQVSNSHTNKLIEDMGLDATKVPLTFPYWGNVAAAALPMTLALEAERLEPGARVLCLGVGSGLNTTLMEIAW',
 'WP_115933252.1_Citricoccus_muralis': 'MVQGNATFRHSNASLLSVTEVLAPVTVTSAQLDEELADVLKGLRLPKGLLPRVAGVNARRNWEHPGHFQLGAAEAGRQALEKAGVRPDQIGLMVNTSVTRETLEPSVAVRIHHEMGLPTSATNFDITNACLGFVNGITLAASMIDSGQVDYAVVVAGEDSVKVQQATLENLKQDGVDRTNFMEQFASLTLGSGAAAAIIGRTDQHPEGHRIVRGITRAGTDHHDLCVGDHKGMFTDSTALLKDGLELVMDAWNDVPADWGWATMDRYVTHQVSRLHTDSITEATGLDPSLFPVTFPELGNVGPASLPITLAREVDQLSAGDKVLCMGVGSGLNTAMLEIAW',
 'ABL00697.1_Pelobacter_propionicus_DSM_2379': 'MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAMTGIRERRWWEPGYPLSQGAIAAARKALAASAVPVDQIGALIYAGVCREQFEPATACRVAHGLGIGGQAAVFDISNACLGVLNGMLDLANRIELGQIRAGMVVSCESAREINEIMIERMLKERRMEHFASSLATLTGGSGAVAVLLTDGSFSGAQRRKLLGGVCLSAPEHHQFCLWGMAPDGRGGYQQVMSTDGVNVMNHGVELGKRTWNAFLPHLGWSAEQVDQVICHQVGSAHQNAILKTLGISADQDFTTYEYLGNMGTVSLPLTAALAAERDILLTGDRVALLGIGSGLNCLMLGVEW',

In [35]:
robinson_data = pd.read_csv("robinson_data.csv")
robinson_data

,id,PC1,PC2,PC3,PC4,PC5,PC6,PC7,polrty_1A_4KU5pos_108,secstr_1B_4KU5pos_108,...,KF2,KF3,KF4,KF5,KF6,KF7,KF8,KF9,KF10,is_active
0,Kytococcus sedentarius_7Ph.heptanoate,-0.693317,0.917505,0.309896,-1.056756,1.229211,-0.080626,0.544235,0.595417,0.465030,...,0.605154,-0.683354,1.059097,-0.471745,1.408643,-0.262595,-0.913467,0.666567,1.017601,Y
1,Granulosicoccus antarcticus_7Ph.heptanoate,-0.693317,0.917505,0.309896,-1.056756,1.229211,-0.080626,0.544235,0.595417,0.465030,...,-0.068726,-0.666975,-0.303272,-0.804958,0.911522,-1.181101,0.363827,1.617761,-0.864156,Y
2,Mobilicoccus massiliensis_7Ph.heptanoate,-0.693317,0.917505,0.309896,-1.056756,1.229211,-0.080626,0.544235,0.595417,0.465030,...,0.077553,0.042100,0.363071,-0.251475,2.173181,-0.317126,0.381304,-1.599134,0.063344,Y
3,Kocuria varians_7Ph.heptanoate,-0.693317,0.917505,0.309896,-1.056756,1.229211,-0.080626,0.544235,0.595417,0.465030,...,-0.345622,-1.158997,-0.127966,-1.031086,0.612161,0.496284,0.558514,-0.333740,0.561629,Y
4,Actinoplanes atraurantiacus_7Ph.heptanoate,-0.693317,0.917505,0.309896,-1.056756,1.229211,-0.080626,0.544235,-2.088078,-2.125494,...,-0.611830,1.461294,0.002922,-0.651472,-0.986643,-0.171566,-0.839157,-0.405522,1.592423,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,Pelobacter propionicus_benzoate,0.464344,-0.538466,1.607430,0.814112,0.695388,0.739246,0.403366,-0.346763,0.468684,...,-0.184432,0.422122,-1.733793,-0.009833,0.472815,2.611540,0.565819,-1.456889,-0.423440,N
1091,Bacteroides luti_benzoate,0.464344,-0.538466,1.607430,0.814112,0.695388,0.739246,0.403366,-0.346763,0.468684,...,2.486878,1.557600,-0.937870,1.528293,-0.920661,-0.353190,-1.291846,1.462778,-1.005155,N
1092,Nonomuraea candida_benzoate,0.464344,-0.538466,1.607430,0.814112,0.695388,0.739246,0.403366,-0.346763,0.468684,...,-1.522843,-0.116781,-1.646922,-1.904094,-0.889459,-1.337534,-2.263066,1.384963,0.984650,N
1093,Legionella brunensis_benzoate,0.464344,-0.538466,1.607430,0.814112,0.695388,0.739246,0.403366,-0.346763,0.468684,...,1.296787,1.293810,-0.167638,1.291767,-0.987850,0.680072,0.109082,0.890316,-1.901134,N
1094,Allokutzneria albata_benzoate,0.464344,-0.538466,1.607430,0.814112,0.695388,0.739246,0.403366,-2.088078,-2.125494,...,-1.152061,0.124690,-1.805003,-0.402121,-1.485201,-2.388355,-0.332669,1.097322,0.799963,N

In [36]:
import pandas as pd
import numpy as np

robinson_data = pd.read_csv("robinson_data.csv")
enzymes = []
enzyme_sequences = []
compounds = []
bindings = []

for i, data in enumerate(robinson_data["id"].str.split("_")):
    compounds.append(data[1].replace(".", " "))
    enzymes.append(data[0])
    enzyme = data[0].replace(" ", "_")
    found = False
    for sequence in sequences:
        if enzyme in sequence:
            enzyme_sequences.append(sequences[sequence])
            found = True
    
    if not found:
        print(enzyme)


    binding = robinson_data.loc[i, "is_active"]
    if binding == "Y":
        binding = 1
    else:
        binding = 0
    
    bindings.append(binding)

In [37]:
len(enzymes), len(compounds), len(enzyme_sequences), len(bindings)

(1095, 1095, 1095, 1095)

In [38]:
import pandas as pd

new_dataset = pd.DataFrame(
    {"Enzyme": enzymes,
     "Compound": compounds,
     "Enzyme_sequence": enzyme_sequences,
     "Binding": bindings}
)
new_dataset

,Enzyme,Compound,Enzyme_sequence,Binding
0,Kytococcus sedentarius,7Ph heptanoate,MPGNATFRHSNTSVLSVTALPAPEVHTSAEFDARIMDTLRRNKLVP...,1
1,Granulosicoccus antarcticus,7Ph heptanoate,MKGCAVSNNFQYQFNDVAIVSIEACDAPVVVTSAAIDEALAPFLER...,1
2,Mobilicoccus massiliensis,7Ph heptanoate,MSENASYRLANCSILSVSTVEAPEVVTSDHLDELLQPAYDTTGMMA...,1
3,Kocuria varians,7Ph heptanoate,MTGNSTITNRNVAILSVTKTEADVVIPSTRFDEELAETFRRLRMPK...,1
4,Actinoplanes atraurantiacus,7Ph heptanoate,MNVGITGIAYALPAREVTTAELQRRVAPKLPPRMFEQATGITRRRV...,1
...,...,...,...,...
1090,Pelobacter propionicus,benzoate,MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAM...,0
1091,Bacteroides luti,benzoate,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,0
1092,Nonomuraea candida,benzoate,MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIER...,0
1093,Legionella brunensis,benzoate,MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEAL...,0
1094,Allokutzneria albata,benzoate,MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTG...,0

In [39]:
new_dataset["Compound"] = new_dataset.Compound.str.replace("oxadiazole", "oxidazole")

In [40]:
import pandas as pd

# Specify the path to your Excel file
file_path = 'final_15_cmpnds_tested.xlsx'

# Read the Excel file
df = pd.read_excel(file_path)
df

,cmpnd_abbrev,IUPAC,SMILES
0,biotin,"4-nitrophenyl 5-((3aS,4S,6aR)-2-oxohexahydro-1...",O=[N+](C1=CC=C(OC(CCCC[C@H]2[C@]([H])([C@]([H]...
1,benzoate,4-nitrophenyl benzoate,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-]
2,dodecanoate,4-nitrophenyl dodecanoate,O=[N+](C1=CC=C(OC(CCCCCCCCCCC)=O)C=C1)[O-]
3,TMA,4-nitrophenyl pivalate,O=[N+](C1=CC=C(OC(C(C)(C)C)=O)C=C1)[O-]
4,7Ph heptanoate,4-nitrophenyl 7-phenylheptanoate,O=[N+](C1=CC=C(OC(CCCCCCC2=CC=CC=C2)=O)C=C1)[O-]
5,heptynoate,4-nitrophenyl hept-6-ynoate,O=[N+](C1=CC=C(OC(CCCCC#C)=O)C=C1)[O-]
6,ClPh propionate,4-nitrophenyl 3-(4-chlorophenoxy)propanoate,O=[N+](C1=CC=C(OC(CCOC2=CC=C(Cl)C=C2)=O)C=C1)[O-]
7,butoxy,4-nitrophenyl 2-(2-butoxyethoxy)acetate,O=C(OC1=CC=C([N+]([O-])=O)C=C1)COCCOCCCC
8,azido,4-nitrophenyl 6-azidohexanoate,O=C(OC1=CC=C([N+]([O-])=O)C=C1)CCCCCN=[N+]=[N-]
9,dimethyl,"4-nitrophenyl 2,2-dimethylhexanoate",CCCCC(C)(C)C(OC1=CC=C([N+]([O-])=O)C=C1)=O
10,oxidazole,"4-nitrophenyl 3-(5-phenyl-1,3,4-oxadiazol-2-yl...",O=C(OC1=CC=C([N+]([O-])=O)C=C1)CCC2=NN=C(C3=CC...
11,cyclopentyl,4-nitrophenyl 3-cyclopentylpropanoate,O=C(OC1=CC=C(C=C1)[N+]([O-])=O)CCC2CCCC2
12,hexanoate,4-nitrophenyl hexanoate,CCCCCC(OC1=CC=C([N+]([O-])=O)C=C1)=O
13,heptanoate,4-nitrophenyl heptanoate,CCCCCCC(OC1=CC=C([N+]([O-])=O)C=C1)=O
14,decanoate,4-nitrophenyl decanoate,CCCCCCCCCC(OC1=CC=C([N+]([O-])=O)C=C1)=O

In [41]:
df.columns = ["Compound", "IUPAC", "SMILES"]

In [42]:
merged = pd.merge(new_dataset, df, on="Compound", how="left")
merged.columns = ["Enzyme ID", "Substrate ID", "Sequence", "Binding", "IUPAC", "SMILES"]
merged

,Enzyme ID,Substrate ID,Sequence,Binding,IUPAC,SMILES
0,Kytococcus sedentarius,7Ph heptanoate,MPGNATFRHSNTSVLSVTALPAPEVHTSAEFDARIMDTLRRNKLVP...,1,4-nitrophenyl 7-phenylheptanoate,O=[N+](C1=CC=C(OC(CCCCCCC2=CC=CC=C2)=O)C=C1)[O-]
1,Granulosicoccus antarcticus,7Ph heptanoate,MKGCAVSNNFQYQFNDVAIVSIEACDAPVVVTSAAIDEALAPFLER...,1,4-nitrophenyl 7-phenylheptanoate,O=[N+](C1=CC=C(OC(CCCCCCC2=CC=CC=C2)=O)C=C1)[O-]
2,Mobilicoccus massiliensis,7Ph heptanoate,MSENASYRLANCSILSVSTVEAPEVVTSDHLDELLQPAYDTTGMMA...,1,4-nitrophenyl 7-phenylheptanoate,O=[N+](C1=CC=C(OC(CCCCCCC2=CC=CC=C2)=O)C=C1)[O-]
3,Kocuria varians,7Ph heptanoate,MTGNSTITNRNVAILSVTKTEADVVIPSTRFDEELAETFRRLRMPK...,1,4-nitrophenyl 7-phenylheptanoate,O=[N+](C1=CC=C(OC(CCCCCCC2=CC=CC=C2)=O)C=C1)[O-]
4,Actinoplanes atraurantiacus,7Ph heptanoate,MNVGITGIAYALPAREVTTAELQRRVAPKLPPRMFEQATGITRRRV...,1,4-nitrophenyl 7-phenylheptanoate,O=[N+](C1=CC=C(OC(CCCCCCC2=CC=CC=C2)=O)C=C1)[O-]
...,...,...,...,...,...,...
1090,Pelobacter propionicus,benzoate,MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAM...,0,4-nitrophenyl benzoate,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-]
1091,Bacteroides luti,benzoate,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,0,4-nitrophenyl benzoate,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-]
1092,Nonomuraea candida,benzoate,MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIER...,0,4-nitrophenyl benzoate,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-]
1093,Legionella brunensis,benzoate,MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEAL...,0,4-nitrophenyl benzoate,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-]
1094,Allokutzneria albata,benzoate,MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTG...,0,4-nitrophenyl benzoate,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-]

In [43]:
merged["Publication"] = ["https://doi.org/10.1093/synbio/ysaa004"]*merged.shape[0]

In [44]:
merged.to_csv("final_dataset.csv", index=False)