In [2]:
import pandas as pd

curated_dataset = pd.read_csv("curated_dataset.csv")
assignments = pd.read_csv("graphpart_assignments_0_2_train_test_split_curated.csv")
assignments

,AC,priority,label-val,between_connectivity,cluster
0,P00509,False,0,0,0.0
1,A0A174XK40,False,0,0,0.0
2,P04693,False,0,0,0.0
3,A0A3N0RMA5,False,0,0,0.0
4,P0A959,False,0,0,0.0
...,...,...,...,...,...
10100,Pelobacter_propionicus,False,0,0,0.0
10101,Bacteroides_luti,False,0,0,0.0
10102,Nonomuraea_candida,False,0,0,0.0
10103,Legionella_brunensis,False,0,0,0.0
10104,Allokutzneria_albata,False,0,0,0.0

In [23]:
train_dataset_ids = assignments[assignments["cluster"]==0]["AC"]
validation_dataset_ids = assignments[assignments["cluster"]==2]["AC"]
test_dataset_ids = assignments[assignments["cluster"]==1]["AC"]

In [24]:
train_dataset = curated_dataset[curated_dataset["Enzyme ID"].isin(train_dataset_ids)]
train_dataset

,Unnamed: 0,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
0,0,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C(C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 1,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
1,1,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 2,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
2,2,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 3,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
3,3,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC(C)C[C@@H](C(=O)O)N,1.0,P00509,compound_aminotransferase_dataset 4,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
4,4,MFENITAAPADPILGLADLFRADERPGKINLGIGVYKDETGKTPVL...,CC[C@H](C)[C@@H](C(=O)O)N,0.0,P00509,compound_aminotransferase_dataset 5,https://pubs.acs.org/doi/10.1021/acscatal.0c01895,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
73225,76466,MKYRAVTLESFGYQLAPVVVSTSDLEARLEPLYRQLRIAPGQLQAM...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Pelobacter_propionicus,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
73226,76467,MAFLSVNNVEIVGLAAAVPKNVETLDNLEFFAPGEAEKVMALTGIK...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Bacteroides_luti,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
73227,76468,MSAPRYSQVSAVAVRLPDEDLTTPELEELLAERNPRVDVPRGLIER...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Nonomuraea_candida,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
73228,76469,MRYQRVFINKIAYELPKEKVATSFLEEQLTDVYQELGIPLGQVEAL...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Legionella_brunensis,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN
73229,76470,MTYSRIGQIAVHLPEGGRTSAEVEALVAELNPGFEPPEGLIERFTG...,C1=CC=C(C=C1)C(=O)OC2=CC=C(C=C2)[N+](=O)[O-],0.0,Allokutzneria_albata,benzoate,https://doi.org/10.1093/synbio/ysaa004,True,NaN,NaN,NaN

In [25]:
proteins_to_add = train_dataset[train_dataset["Binding"] == 0].drop_duplicates(subset=["Enzyme ID"]).loc[:, ["Enzyme ID"]].sample(frac=0.1)

In [26]:
from plants_sm.io.pickle import read_pickle, write_pickle

splits = read_pickle("splits_0_2_proteins_train_val_test.pkl")

In [27]:
proteins_to_add

      Enzyme ID
16290    Q97Q24
37102    I3ICT0
41782     KCE18
54062  KP347726
10845    Q5QXU4
...         ...
25200    Q97TM8
40269    KCE364
41459    KCE388
20416    P44755
69467   UGT72B1

[73 rows x 1 columns]

In [32]:
train_ids = splits[0][0]
train_ids = train_ids[~train_ids.isin(proteins_to_add["Enzyme ID"])]

In [33]:
validation_ids = splits[0][1]
validation_ids = pd.concat([validation_ids, proteins_to_add["Enzyme ID"]])
test_ids = splits[0][2]

In [35]:
write_pickle(
    
    "splits_0_2_proteins_train_val_test_curated_changed.pkl",
    [
        (train_ids, validation_ids, test_ids),
    ]
)

True

In [5]:
validation_dataset = curated_dataset[curated_dataset["Enzyme ID"].isin(validation_dataset_ids)]
validation_dataset

,Unnamed: 0,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
54191,54191,MAIKENAAQEVLEVQKVIDRLADNGQKALKAFESYNQEQVDNIVHA...,CC(C)O,1.0,Q6Q3I1,CHEBI:35681,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
54192,54192,MAIKENAAQEVLEVQKVIDRLADNGQKALKAFESYNQEQVDNIVHA...,N=C([O-])c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(...,1.0,Q6Q3I1,CHEBI:57540,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
54201,54202,MKVTNQKELKQKLNELREAQKKFATYTQEQVDKIFKQCAIAAAKER...,CC(C)O,1.0,Q9ANR5,CHEBI:35681,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
54202,54203,MKVTNQKELKQKLNELREAQKKFATYTQEQVDKIFKQCAIAAAKER...,N=C([O-])c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(...,1.0,Q9ANR5,CHEBI:57540,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
54203,54204,MKVTNQKELKQKLNELREAQKKFATYTQEQVDKIFKQCAIAAAKER...,C=O,1.0,Q9ANR5,CHEBI:17478,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
69186,71818,MSAGRLWSSLLLLLPLFCSKSSSCGLSTHVEIGHRALEFLRLQDGR...,N[C@H]1[C@@H](O[C@@H]2[C@@H](O)[C@H](O)[C@@H](...,1.0,O70362,CHEBI:57997,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69225,71858,MAGRITINGTSHEVNLSALPADISLNTFIREYAGLTGTKFMCQEGG...,Cc1ncc(CO)c(C=O)c1O,1.0,Q9VF53,CHEBI:17310,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69240,71874,MAEWLLSASWQRRAKAMTAAAGSAGRAAVPLLLCALLAPGGAYVLD...,CCCCCCCCCCCCC/C=C/[C@@H](O)[C@H](CO[C@@H]1O[C@...,1.0,P54803,CHEBI:18390,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69258,71893,MAEIGFASTTGASFAPDVRRRNVRTEGQARTSGLIEPDDKKHKQRP...,CC(C)=CCC/C(C)=C/CC/C(C)=C/CC/C(C)=C\CCC(C)CCO...,1.0,G5EB59,C03862,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69262,71897,MRKTTLFLAVTFATSNAQGRALRSSSPATYGTTDGSDYILKTGYLI...,C[C@@H]1O[C@@H](O)[C@@H](O)[C@H](O)[C@@H]1O,1.0,Q5AU81,CHEBI:28349,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN

In [6]:
test_dataset = curated_dataset[curated_dataset["Enzyme ID"].isin(test_dataset_ids)]
test_dataset

,Unnamed: 0,Sequence,SMILES,Binding,Enzyme ID,Substrate ID,Publication,Validated,RHEA_ID,EC number,reaction_SMILES
15300,15300,MKTYIKRLNWEESIYLAINKLIAKHGKDNEAYNPDNKPFAVFDWDN...,C=C(OP(=O)(O)O)C(=O)O,0.0,C7RF86,compound_phospatase_dataset 1,https://doi.org/10.1073/pnas.1423570112,True,NaN,NaN,NaN
15301,15301,MKTYIKRLNWEESIYLAINKLIAKHGKDNEAYNPDNKPFAVFDWDN...,CC(=O)N[C@@H]1C(O)O[C@H](COP(=O)(O)O)[C@@H](O)...,0.0,C7RF86,compound_phospatase_dataset 2,https://doi.org/10.1073/pnas.1423570112,True,NaN,NaN,NaN
15302,15302,MKTYIKRLNWEESIYLAINKLIAKHGKDNEAYNPDNKPFAVFDWDN...,CC(=O)N[C@@H]1[C@@H](O)CC(O)(C(=O)O)O[C@H]1[C@...,0.0,C7RF86,compound_phospatase_dataset 3,https://doi.org/10.1073/pnas.1423570112,True,NaN,NaN,NaN
15303,15303,MKTYIKRLNWEESIYLAINKLIAKHGKDNEAYNPDNKPFAVFDWDN...,CC(=O)OP(=O)(O)O,0.0,C7RF86,compound_phospatase_dataset 4,https://doi.org/10.1073/pnas.1423570112,True,NaN,NaN,NaN
15304,15304,MKTYIKRLNWEESIYLAINKLIAKHGKDNEAYNPDNKPFAVFDWDN...,CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]1O[C@@H](n2cnc...,0.0,C7RF86,compound_phospatase_dataset 5,https://doi.org/10.1073/pnas.1423570112,True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
69212,71845,MLRNLVVRNACRNRPSIQVARGLCRHQTRRLMASSPQFGRNSNQEK...,CS,1.0,P36046,CHEBI:16520,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69214,71847,MRLRTAIATLCLTAFTSATSNNSYIATDQTQNAFNDTHFCKVDRND...,CS,1.0,Q03103,CHEBI:16520,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69236,71870,MFKNPNIRYHKLSSKSNDNDQESSHRCKHILLFIITLFLLIVGLYI...,O=C(/C=C/c1ccc(O)cc1)c1c(O)cc(O)cc1O,1.0,Q9FRX6,C06561,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69247,71882,MLSLDVLLLCAISGFQLLISADGDPMIEVFKWKQLDFYNRGDGYKD...,O=C1C=C2C[C@@H](C(=O)[O-])NC2=CC1=O,1.0,Q9VG09,CHEBI:57509,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN
69270,71905,MRLRKYNKSLGWLSLFAGTVLLSGCNSALLDPKGQIGLEQRSLILT...,COc1c(O)c(C)c(CC=C(C)C)c(O)c1OC,1.0,P0ABJ1,CHEBI:17976,https://doi.org/10.1038/s41467-023-38347-2,True,NaN,NaN,NaN