In [2]:
import pandas as pd

df = pd.read_csv("results_esp_original_dataset.csv")
df.describe()

       accuracy  f1_score    recall  precision   roc_auc       mcc      seed
count  5.000000  5.000000  5.000000   5.000000  5.000000  5.000000  5.000000
mean   0.917623  0.845261  0.844485   0.846042  0.957823  0.789135  2.000000
std    0.001203  0.002163  0.002235   0.002971  0.000646  0.002991  1.581139
min    0.916077  0.842571  0.842041   0.842186  0.957162  0.785361  0.000000
25%    0.916972  0.844322  0.842958   0.843550  0.957163  0.787713  1.000000
50%    0.917623  0.844880  0.844485   0.847739  0.957889  0.788811  2.000000
75%    0.918193  0.846166  0.845096   0.847853  0.958402  0.790450  3.000000
max    0.919251  0.848364  0.847846   0.848883  0.958497  0.793339  4.000000

In [3]:
import pandas as pd

df = pd.read_csv("results_np_classifier.csv")
df.describe()

           seed  f1_macro  precision   roc_auc  accuracy       mcc    recall
count  5.000000  5.000000   5.000000  5.000000  5.000000  5.000000  5.000000
mean   2.000000  0.769499   0.754599  0.927808  0.874919  0.684034  0.785140
std    1.581139  0.026639   0.020044  0.015150  0.013212  0.035616  0.034432
min    0.000000  0.723417   0.719711  0.901389  0.851978  0.622385  0.727162
25%    1.000000  0.774414   0.755356  0.929730  0.876783  0.690148  0.787759
50%    2.000000  0.776411   0.765385  0.933783  0.879215  0.693828  0.794458
75%    3.000000  0.781325   0.765789  0.934920  0.881161  0.700053  0.797503
max    4.000000  0.791930   0.766752  0.939218  0.885457  0.713758  0.818819